#!/usr/bin/env python3
"""
Align phrases across all 3 language files (phrases-de-DE.yaml, phrases-en-GB.yaml, phrases-fr-FR.yaml).

1. Fixes wrong ❓ emoji assignments in phrases-en-GB.yaml
2. Adds missing translations for each language
3. Uses espeak-ng for IPA generation (de, fr, en-gb)
"""

import subprocess
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).parent.parent


def get_espeak_ipa(text: str, lang_code: str) -> str:
    """Get IPA from espeak-ng. lang_code: 'de', 'fr', 'en-gb'"""
    result = subprocess.run(
        ["espeak-ng", "-v", lang_code, "--ipa", "-q", text],
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def load_yaml(path: Path) -> list:
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def save_yaml(path: Path, data: list) -> None:
    with open(path, "w", encoding="utf-8") as f:
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False, width=120)


# ---------------------------------------------------------------------------
# Step 1: Fix wrong ❓ emoji assignments in phrases-en-GB.yaml
# These phrases exist in EN but have the wrong emoji (❓ placeholder)
# ---------------------------------------------------------------------------
EMOJI_FIXES = {
    "arts": "🎨",
    "balloon": "🎈",
    "bamboo": "🎋",
    "bright": "🔆",
    "diamond": "💎",
    "dim": "🔅",
    "globe": "🌍",
    "lift": "🛗",
    "mate": "🤝",
    "mountain": "🏔️",
    "sofa": "🛋️",
    "wrestle": "🤼",
    # "question" intentionally keeps ❓
}


# ---------------------------------------------------------------------------
# Step 2: New German phrases to add
# Format: (phrase, emoji)  — IPA will be generated by espeak-ng
# ---------------------------------------------------------------------------
NEW_DE = [
    # DE+EN-not-FR: already in DE, but adding here would be duplicates — skip.
    # EN-only → need DE translations:
    ("Null", "0️⃣"),
    ("Die Tastatur", "⌨️"),
    ("Der Schneemann", "☃️"),
    ("Der Komet", "☄️"),
    ("Der Klee", "☘️"),
    ("Frieden", "☮️"),
    ("Krebs", "♋"),
    ("Der Anker", "⚓"),
    ("Die Waage", "⚖️"),
    ("Das Zahnrad", "⚙️"),
    ("Das Atom", "⚛️"),
    ("Die Warnung", "⚠️"),
    ("Der Sarg", "⚰️"),
    ("Das Gewitter", "⛈️"),
    ("Die Spitzhacke", "⛏️"),
    ("Die Kette", "⛓️"),
    ("Kein Zutritt", "⛔"),
    ("Der Sonnenschirm", "⛱️"),
    ("Der Brunnen", "⛲"),
    ("Die Fähre", "⛴️"),
    ("Der Kraftstoff", "⛽"),
    ("Die Schere", "✂️"),
    ("Das Häkchen", "✅"),
    ("Sieg", "✌️"),
    ("Schreiben", "✍️"),
    ("Das Kreuz", "✝️"),
    ("Funkeln", "✨"),
    ("Die Frage", "❓"),
    ("Der Kreis", "⭕"),
    ("Cool", "🆒"),
    ("Kostenlos", "🆓"),
    ("Neu", "🆕"),
    ("Oben", "🆙"),
    ("Service", "🈂️"),
    ("Reserviert", "🈯"),
    ("Bestanden", "🈴"),
    ("Voll", "🈵"),
    ("Akzeptiert", "🉑"),
    ("Der Wirbelsturm", "🌀"),
    ("Der Blitz", "🌩️"),
    ("Der Tornado", "🌪️"),
    ("Die Kastanie", "🌰"),
    ("Der Kaktus", "🌵"),
    ("Die Chilischote", "🌶️"),
    ("Der Mais", "🌽"),
    ("Das Getreide", "🌾"),
    ("Das Kraut", "🌿"),
    ("Die Melone", "🍈"),
    ("Die Ananas", "🍍"),
    ("Der Pfirsich", "🍑"),
    ("Das Reisbällchen", "🍙"),
    ("Das Curry", "🍛"),
    ("Die Garnele", "🍤"),
    ("Das Eis", "🍧"),
    ("Der Pudding", "🍮"),
    ("Der Wein", "🍷"),
    ("Der Cocktail", "🍸"),
    ("Die Babyflasche", "🍼"),
    ("Die Party", "🎉"),
    ("Das Konfetti", "🎊"),
    ("Die Puppen", "🎎"),
    ("Der Karpfen", "🎏"),
    ("Das Windspiel", "🎐"),
    ("Das Mikrofon", "🎙️"),
    ("Der Film", "🎞️"),
    ("Das Riesenrad", "🎡"),
    ("Die Achterbahn", "🎢"),
    ("Das Kino", "🎦"),
    ("Der Zirkus", "🎪"),
    ("Das Spiel", "🎮"),
    ("Billard", "🎱"),
    ("Der Würfel", "🎲"),
    ("Die Note", "🎵"),
    ("Das Saxofon", "🎷"),
    ("Die Partitur", "🎼"),
    ("Das Sporthemd", "🎽"),
    ("Der Ski", "🎿"),
    ("Basketball", "🏀"),
    ("Der Läufer", "🏃"),
    ("Surfen", "🏄"),
    ("American Football", "🏈"),
    ("Rugby", "🏉"),
    ("Schwimmen", "🏊"),
    ("Cricket", "🏏"),
    ("Hockey", "🏒"),
    ("Das Museum", "🏛️"),
    ("Das Büro", "🏢"),
    ("Das Postamt", "🏣"),
    ("Die Bank", "🏦"),
    ("Das Hotel", "🏨"),
    ("Das Geschäft", "🏬"),
    ("Die Fabrik", "🏭"),
    ("Das Etikett", "🏷️"),
    ("Bogenschießen", "🏹"),
    ("Der Büffel", "🐃"),
    ("Der Leopard", "🐆"),
    ("Der Oktopus", "🐙"),
    ("Die Raupe", "🐛"),
    ("Der Koala", "🐨"),
    ("Der Pudel", "🐩"),
    ("Das Kamel", "🐪"),
    ("Die Augen", "👀"),
    ("Nach unten", "👇"),
    ("Nach rechts", "👉"),
    ("Die Faust", "👊"),
    ("Winken", "👋"),
    ("Die Krone", "👑"),
    ("Die Krawatte", "👔"),
    ("Das Portemonnaie", "👛"),
    ("Die Handtasche", "👜"),
    ("Die Clutch", "👝"),
    ("Der Absatz", "👠"),
    ("Der Stiefel", "👢"),
    ("Blind", "👨‍🦯"),
    ("Die Familie", "👪"),
    ("Das Paar", "👫"),
    ("Die Häschen", "👯"),
    ("Die Braut", "👰"),
    ("Die Prinzessin", "👸"),
    ("Der Engel", "👼"),
    ("Der Wächter", "💂"),
    ("Der Tanz", "💃"),
    ("Der Lippenstift", "💄"),
    ("Die Spritze", "💉"),
    ("Die Pille", "💊"),
    ("Der Ring", "💍"),
    ("Der Diamant", "💎"),
    ("Der Kuss", "💏"),
    ("Die Wut", "💢"),
    ("Die Bombe", "💣"),
    ("Schlaf", "💤"),
    ("Schwindel", "💫"),
    ("Die Kreditkarte", "💳"),
    ("Der Dollar", "💵"),
    ("Das Pfund", "💷"),
    ("Der Sitz", "💺"),
    ("Der Ordner", "📁"),
    ("Der Kalender", "📅"),
    ("Das Lineal", "📏"),
    ("Das Dreieck", "📐"),
    ("Das Notizbuch", "📔"),
    ("Der Name", "📛"),
    ("Das Signal", "📶"),
    ("Das Video", "📹"),
    ("Das Radio", "📻"),
    ("Die Kassette", "📼"),
    ("Der Projektor", "📽️"),
    ("Die Batterie", "🔋"),
    ("Der Stecker", "🔌"),
    ("Das Schloss", "🔒"),
    ("Der Schraubenschlüssel", "🔧"),
    ("Die Pistole", "🔫"),
    ("Das Mikroskop", "🔬"),
    ("Die Taube", "🕊️"),
    ("Die Moschee", "🕌"),
    ("Die Synagoge", "🕍"),
    ("Die Kerze", "🕯️"),
    ("Der Anzug", "🕴️"),
    ("Der Pinsel", "🖌️"),
    ("Der Buntstift", "🖍️"),
    ("Der Mittelfinger", "🖕"),
    ("Die Computermaus", "🖱️"),
    ("Die Box", "🗃️"),
    ("Der Schrank", "🗄️"),
    ("Der Mülleimer", "🗑️"),
    ("Der Notizblock", "🗒️"),
    ("Das Schwert", "🗡️"),
    ("Sprechen", "🗣️"),
    ("Der Turm", "🗼"),
    ("Die Freiheitsstatue", "🗽"),
    ("Die Statue", "🗿"),
    ("Verbeugen", "🙇"),
    ("Melden", "🙋"),
    ("Stirnrunzeln", "🙍"),
    ("Beten", "🙏"),
    ("Die Straßenbahn", "🚋"),
    ("Die Haltestelle", "🚏"),
    ("Der Kleinbus", "🚐"),
    ("Der Krankenwagen", "🚑"),
    ("Das Polizeiauto", "🚓"),
    ("Das Taxi", "🚕"),
    ("Der Lastwagen", "🚛"),
    ("Der Traktor", "🚜"),
    ("Die Ampel", "🚦"),
    ("Die Baustelle", "🚧"),
    ("Die Zigarette", "🚬"),
    ("Kein Abfall", "🚯"),
    ("Kein Trinkwasser", "🚱"),
    ("Fahrradfahren", "🚴"),
    ("Kinder", "🚸"),
    ("Frauen", "🚺"),
    ("Das Baby", "🚼"),
    ("Die Toilette", "🚽"),
    ("Das Bad", "🛀"),
    ("Das Gepäck", "🛄"),
    ("Die Gepäckaufbewahrung", "🛅"),
    ("Der Gottesdienst", "🛐"),
    ("Der Tempel", "🛕"),
    ("Der Aufzug", "🛗"),
    ("Das Schild", "🛡️"),
    ("Das Fass", "🛢️"),
    ("Der Roller", "🛴"),
    ("Das Kanu", "🛶"),
    ("Kneifen", "🤏"),
    ("Rock", "🤘"),
    ("Anruf", "🤙"),
    ("Daumen drücken", "🤞"),
    ("Liebe", "🤟"),
    ("Offene Hände", "🤲"),
    ("Der Prinz", "🤴"),
    ("Achselzucken", "🤷"),
    ("Jonglieren", "🤹"),
    ("Fechten", "🤺"),
    ("Das Tor", "🥅"),
    ("Boxen", "🥊"),
    ("Kampfsport", "🥋"),
    ("Der Speck", "🥓"),
    ("Der Pfannkuchen", "🥞"),
    ("Die Tarte", "🥧"),
    ("Die Brezel", "🥨"),
    ("Das Steak", "🥩"),
    ("Der Kopfsalat", "🥬"),
    ("Der Laborkittel", "🥼"),
    ("Die Schutzbrille", "🥽"),
    ("Die Krabbe", "🦀"),
    ("Der Skorpion", "🦂"),
    ("Das Einhorn", "🦄"),
    ("Der Gorilla", "🦍"),
    ("Die Eidechse", "🦎"),
    ("Das Nashorn", "🦏"),
    ("Der Tintenfisch", "🦑"),
    ("Der Dinosaurier", "🦖"),
    ("Das Nilpferd", "🦛"),
    ("Der Schwan", "🦢"),
    ("Der Stock", "🦯"),
    ("Der Knochen", "🦴"),
    ("Die Sicherheitsweste", "🦺"),
    ("Der Roboterarm", "🦾"),
    ("Der Knoblauch", "🧄"),
    ("Stehen", "🧍"),
    ("Knien", "🧎"),
    ("Gehörlos", "🧏"),
    ("Die Person", "🧑"),
    ("Die ältere Person", "🧓"),
    ("Die Sauna", "🧖"),
    ("Klettern", "🧗"),
    ("Die Fee", "🧚"),
    ("Der Vampir", "🧛"),
    ("Der Elf", "🧝"),
    ("Das rote Kuvert", "🧧"),
    ("Der Kompass", "🧭"),
    ("Der Feuerlöscher", "🧯"),
    ("Die Sicherheitsnadel", "🧷"),
    ("Der Besen", "🧹"),
    ("Der Korb", "🧺"),
    ("Das Toilettenpapier", "🧻"),
    ("Der Schwamm", "🧽"),
    ("Das Pflaster", "🩹"),
    ("Das Stethoskop", "🩺"),
    ("Der Fallschirm", "🪂"),
    ("Der Rasierer", "🪒"),
    ("Die Axt", "🪓"),
    ("Die Öllampe", "🪔"),
    ("Das Banjo", "🪕"),
    ("Die Leiter", "🪜"),
    ("Der Spiegel", "🪞"),
    # DE-only emojis — need EN and FR, but for DE they already exist.
    # FR-only emojis — need DE and EN:
    ("Die Pommes", "🍟"),
    ("Der Zylinder", "🎩"),
    ("Das Motorrad", "🏍️"),
    ("Die Landschaft", "🏞️"),
    ("Der Tiger", "🐯"),
    ("Das Sofa", "🛋️"),
    ("Orange", "🟠"),
    # New emoji: 🎈 balloon (was DE-only, now EN gets it fixed)
    # DE already has "Der Luftballon" / "Luftballon" — no need to add
    # New: 🏔️ mountain (EN fixes ❓ → 🏔️), DE needs this
    ("Der Berg", "🏔️"),
    # New: 💎 diamond (EN fixes ❓ → 💎), DE needs this (added above)
    # New: 🛗 elevator/lift (EN fixes ❓ → 🛗), DE added above
    # New: 🛋️ sofa (EN fixes ❓ → 🛋️), DE added above
    # New: 🌍 globe (EN fixes ❓ → 🌍), DE needs this
    ("Die Erdkugel", "🌍"),
    # New: 🤝 mate/handshake (EN fixes ❓ → 🤝), DE needs this
    ("Der Handschlag", "🤝"),
    # New: 🤼 wrestle (EN fixes ❓ → 🤼), DE needs this
    ("Ringen", "🤼"),
    # New: 🔆 bright (EN fixes ❓ → 🔆)
    ("Hell", "🔆"),
    # New: 🔅 dim (EN fixes ❓ → 🔅)
    ("Dunkel", "🔅"),
    # New: 🎨 arts (EN fixes ❓ → 🎨)
    ("Die Kunst", "🎨"),
    # New: 🎋 bamboo (EN fixes ❓ → 🎋)
    ("Der Bambus", "🎋"),
]

# ---------------------------------------------------------------------------
# Step 2b: New English phrases to add (truly new — not just emoji fixes)
# ---------------------------------------------------------------------------
NEW_EN = [
    # DE-only emojis:
    ("cookie", "🍪"),
    ("cow", "🐄"),
    ("mouse", "🐭"),
    ("t-shirt", "👕"),
    ("baby", "👶"),
    ("book", "📕"),
    # FR-only emojis:
    ("church", "⛪"),
    ("fries", "🍟"),
    ("top hat", "🎩"),
    ("motorcycle", "🏍️"),
    ("landscape", "🏞️"),
    ("tiger", "🐯"),
    # 🛋️ sofa — fixed from ❓ to 🛋️ (not truly new)
    ("orange", "🟠"),
    # 🎈 balloon — fixed from ❓ to 🎈 (not truly new)
    # 🏔️ mountain — fixed from ❓ to 🏔️ (not truly new)
    # 🌍 globe — fixed from ❓ to 🌍 (not truly new)
]

# ---------------------------------------------------------------------------
# Step 2c: New French phrases to add
# ---------------------------------------------------------------------------
NEW_FR = [
    # DE+EN-not-FR (70 emojis):
    ("La montre", "⌚"),
    ("Le parapluie", "☂️"),
    ("Le ballon de foot", "⚽"),
    ("La tente", "⛺"),
    ("La main", "✋"),
    ("Le crayon à papier", "✏️"),
    ("Le cœur", "❤️"),
    ("La neige tombante", "🌨️"),
    ("Le vent qui souffle", "🌬️"),
    ("La fleur", "🌸"),
    ("La rose", "🌹"),
    ("La feuille d'automne", "🍁"),
    ("La pastèque", "🍉"),
    ("Le hamburger", "🍔"),
    ("La viande", "🍖"),
    ("Les pâtes", "🍝"),
    ("Le beignet", "🍩"),
    ("Le bonbon", "🍭"),
    ("La bière", "🍺"),
    ("Le cadeau", "🎁"),
    ("La guitare", "🎸"),
    ("Le piano", "🎹"),
    ("La trompette", "🎺"),
    ("Le violon", "🎻"),
    ("Le tennis", "🎾"),
    ("Le chantier", "🏗️"),
    ("Le crocodile", "🐊"),
    ("La chèvre", "🐐"),
    ("Le coq", "🐓"),
    ("Le chien", "🐕"),
    ("Le hamster", "🐹"),
    ("La langue", "👅"),
    ("Le chapeau", "👒"),
    ("Le garçon", "👦"),
    ("La fille", "👧"),
    ("L'homme", "👨"),
    ("La femme", "👩"),
    ("La chapelle", "💒"),
    ("L'argent", "💰"),
    ("L'ordinateur", "💻"),
    ("La feuille de papier", "📃"),
    ("Le téléphone", "📱"),
    ("L'appareil photo", "📷"),
    ("La télévision", "📺"),
    ("Le marteau", "🔨"),
    ("Le couteau", "🔪"),
    ("Le télescope", "🔭"),
    ("L'horloge", "🕐"),
    ("Le stylo", "🖊️"),
    ("La fusée", "🚀"),
    ("L'hélicoptère", "🚁"),
    ("Le bateau à moteur", "🚤"),
    ("La batterie de musique", "🥁"),
    ("La salade", "🥗"),
    ("La cacahuète", "🥜"),
    ("Le kiwi", "🥝"),
    ("Le brocoli", "🥦"),
    ("La chauve-souris", "🦇"),
    ("Le requin", "🦈"),
    ("Le cerf", "🦌"),
    ("Le kangourou", "🦘"),
    ("Le paon", "🦚"),
    ("Le perroquet", "🦜"),
    ("Le flamant rose", "🦩"),
    ("Le pied", "🦶"),
    ("L'oignon", "🧅"),
    ("La gaufre", "🧇"),
    ("L'enfant", "🧒"),
    ("L'aimant", "🧲"),
    ("L'ours en peluche", "🧸"),
    # EN-only emojis (267):
    ("Zéro", "0️⃣"),
    ("Le clavier", "⌨️"),
    ("Le bonhomme de neige", "☃️"),
    ("La comète", "☄️"),
    ("Le trèfle", "☘️"),
    ("La paix", "☮️"),
    ("Le cancer", "♋"),
    ("L'ancre", "⚓"),
    ("La balance", "⚖️"),
    ("L'engrenage", "⚙️"),
    ("L'atome", "⚛️"),
    ("L'avertissement", "⚠️"),
    ("Le cercueil", "⚰️"),
    ("L'orage", "⛈️"),
    ("Le pic", "⛏️"),
    ("La chaîne", "⛓️"),
    ("Interdit", "⛔"),
    ("Le parasol", "⛱️"),
    ("La fontaine", "⛲"),
    ("Le golf", "⛳"),
    ("Le ferry", "⛴️"),
    ("Le carburant", "⛽"),
    ("Les ciseaux", "✂️"),
    ("La coche", "✅"),
    ("La victoire", "✌️"),
    ("L'écriture", "✍️"),
    ("La croix", "✝️"),
    ("Les étoiles filantes", "✨"),
    ("La question", "❓"),
    ("Le cercle", "⭕"),
    ("Cool", "🆒"),
    ("Gratuit", "🆓"),
    ("Nouveau", "🆕"),
    ("En haut", "🆙"),
    ("Service", "🈂️"),
    ("Réservé", "🈯"),
    ("Reçu", "🈴"),
    ("Complet", "🈵"),
    ("Accepté", "🉑"),
    ("Le cyclone", "🌀"),
    ("L'éclair", "🌩️"),
    ("La tornade", "🌪️"),
    ("La châtaigne", "🌰"),
    ("Le cactus", "🌵"),
    ("Le piment", "🌶️"),
    ("Le maïs", "🌽"),
    ("Le blé", "🌾"),
    ("L'herbe aromatique", "🌿"),
    ("Le melon", "🍈"),
    ("L'ananas", "🍍"),
    ("La pêche", "🍑"),
    ("La boule de riz", "🍙"),
    ("Le curry", "🍛"),
    ("La crevette", "🍤"),
    ("Le sorbet", "🍧"),
    ("Le pudding", "🍮"),
    ("Le vin", "🍷"),
    ("Le cocktail", "🍸"),
    ("Le biberon", "🍼"),
    ("La fête", "🎉"),
    ("Les confettis", "🎊"),
    ("Les poupées", "🎎"),
    ("La carpe", "🎏"),
    ("Le carillon", "🎐"),
    ("Le microphone", "🎙️"),
    ("Le film", "🎞️"),
    ("La grande roue", "🎡"),
    ("Les montagnes russes", "🎢"),
    ("Le cinéma", "🎦"),
    ("Le cirque", "🎪"),
    ("Le jeu vidéo", "🎮"),
    ("Le billard", "🎱"),
    ("Le dé", "🎲"),
    ("La note de musique", "🎵"),
    ("Le saxophone", "🎷"),
    ("La partition", "🎼"),
    ("Le maillot de sport", "🎽"),
    ("Le ski", "🎿"),
    ("Le basketball", "🏀"),
    ("La course à pied", "🏃"),
    ("Le surf", "🏄"),
    ("Le football américain", "🏈"),
    ("Le rugby", "🏉"),
    ("La natation", "🏊"),
    ("Le cricket", "🏏"),
    ("Le hockey", "🏒"),
    ("Le musée", "🏛️"),
    ("Le bureau", "🏢"),
    ("La poste", "🏣"),
    ("La banque", "🏦"),
    ("L'hôtel", "🏨"),
    ("Le magasin", "🏬"),
    ("L'usine", "🏭"),
    ("L'étiquette", "🏷️"),
    ("Le tir à l'arc", "🏹"),
    ("Le buffle", "🐃"),
    ("Le léopard", "🐆"),
    ("La pieuvre", "🐙"),
    ("La chenille", "🐛"),
    ("Le koala", "🐨"),
    ("Le caniche", "🐩"),
    ("Le chameau", "🐪"),
    ("Les yeux", "👀"),
    ("Vers le bas", "👇"),
    ("Vers la droite", "👉"),
    ("Le poing", "👊"),
    ("Le signe de la main", "👋"),
    ("La couronne", "👑"),
    ("La cravate", "👔"),
    ("Le porte-monnaie", "👛"),
    ("Le sac à main", "👜"),
    ("La pochette", "👝"),
    ("La chaussure à talon", "👠"),
    ("La botte", "👢"),
    ("Aveugle", "👨‍🦯"),
    ("La famille", "👪"),
    ("Le couple", "👫"),
    ("Les danseurs", "👯"),
    ("La mariée", "👰"),
    ("La princesse", "👸"),
    ("L'ange", "👼"),
    ("Le garde", "💂"),
    ("La danse", "💃"),
    ("Le rouge à lèvres", "💄"),
    ("La seringue", "💉"),
    ("Le comprimé", "💊"),
    ("L'anneau", "💍"),
    ("Le diamant", "💎"),
    ("Le baiser", "💏"),
    ("La colère", "💢"),
    ("La bombe", "💣"),
    ("Le sommeil", "💤"),
    ("Le vertige", "💫"),
    ("La carte de crédit", "💳"),
    ("Le dollar", "💵"),
    ("La livre sterling", "💷"),
    ("Le siège", "💺"),
    ("Le dossier", "📁"),
    ("Le calendrier", "📅"),
    ("La règle", "📏"),
    ("L'équerre", "📐"),
    ("Le carnet", "📔"),
    ("Le badge", "📛"),
    ("Le signal", "📶"),
    ("La vidéo", "📹"),
    ("La radio", "📻"),
    ("La cassette", "📼"),
    ("Le projecteur", "📽️"),
    ("La batterie électrique", "🔋"),
    ("La prise électrique", "🔌"),
    ("Le verrou", "🔒"),
    ("La clé à molette", "🔧"),
    ("Le pistolet", "🔫"),
    ("Le microscope", "🔬"),
    ("La colombe", "🕊️"),
    ("La mosquée", "🕌"),
    ("La synagogue", "🕍"),
    ("La bougie", "🕯️"),
    ("Le costume", "🕴️"),
    ("Le pinceau", "🖌️"),
    ("Le crayon de couleur", "🖍️"),
    ("Le doigt d'honneur", "🖕"),
    ("La souris d'ordinateur", "🖱️"),
    ("La boîte de rangement", "🗃️"),
    ("L'armoire", "🗄️"),
    ("La poubelle", "🗑️"),
    ("Le bloc-notes", "🗒️"),
    ("L'épée", "🗡️"),
    ("La parole", "🗣️"),
    ("La tour", "🗼"),
    ("La statue de la Liberté", "🗽"),
    ("La statue", "🗿"),
    ("S'incliner", "🙇"),
    ("Lever la main", "🙋"),
    ("Faire la tête", "🙍"),
    ("Prier", "🙏"),
    ("Le tramway", "🚋"),
    ("L'arrêt de bus", "🚏"),
    ("Le minibus", "🚐"),
    ("L'ambulance", "🚑"),
    ("La voiture de police", "🚓"),
    ("Le taxi", "🚕"),
    ("Le camion", "🚛"),
    ("Le tracteur", "🚜"),
    ("Le feu rouge", "🚦"),
    ("Le chantier de construction", "🚧"),
    ("La cigarette", "🚬"),
    ("Pas de déchets", "🚯"),
    ("Eau non potable", "🚱"),
    ("Le cyclisme", "🚴"),
    ("Les enfants", "🚸"),
    ("Les femmes", "🚺"),
    ("Le bébé", "🚼"),
    ("Les toilettes", "🚽"),
    ("Le bain", "🛀"),
    ("Les bagages", "🛄"),
    ("La consigne à bagages", "🛅"),
    ("Le lieu de culte", "🛐"),
    ("Le temple", "🛕"),
    ("L'ascenseur", "🛗"),
    ("Le bouclier", "🛡️"),
    ("Le tonneau", "🛢️"),
    ("La trottinette", "🛴"),
    ("Le canoë", "🛶"),
    ("Pincer", "🤏"),
    ("Rock", "🤘"),
    ("L'appel", "🤙"),
    ("Les doigts croisés", "🤞"),
    ("L'amour", "🤟"),
    ("Les mains ouvertes", "🤲"),
    ("Le prince", "🤴"),
    ("Le haussement d'épaules", "🤷"),
    ("Le jonglage", "🤹"),
    ("L'escrime", "🤺"),
    ("Le but", "🥅"),
    ("La boxe", "🥊"),
    ("Les arts martiaux", "🥋"),
    ("Le bacon", "🥓"),
    ("La crêpe", "🥞"),
    ("La tarte", "🥧"),
    ("Le bretzel", "🥨"),
    ("Le steak", "🥩"),
    ("La laitue", "🥬"),
    ("La blouse de laboratoire", "🥼"),
    ("Les lunettes de protection", "🥽"),
    ("Le crabe", "🦀"),
    ("Le scorpion", "🦂"),
    ("La licorne", "🦄"),
    ("Le gorille", "🦍"),
    ("Le lézard", "🦎"),
    ("Le rhinocéros", "🦏"),
    ("Le calmar", "🦑"),
    ("Le dinosaure", "🦖"),
    ("L'hippopotame", "🦛"),
    ("Le cygne", "🦢"),
    ("La canne", "🦯"),
    ("L'os", "🦴"),
    ("Le gilet de sécurité", "🦺"),
    ("Le bras robotique", "🦾"),
    ("L'ail", "🧄"),
    ("Debout", "🧍"),
    ("S'agenouiller", "🧎"),
    ("Sourd", "🧏"),
    ("La personne", "🧑"),
    ("La personne âgée", "🧓"),
    ("Le sauna", "🧖"),
    ("L'escalade", "🧗"),
    ("La fée", "🧚"),
    ("Le vampire", "🧛"),
    ("L'elfe", "🧝"),
    ("L'enveloppe rouge", "🧧"),
    ("La boussole", "🧭"),
    ("L'extincteur", "🧯"),
    ("L'épingle à nourrice", "🧷"),
    ("Le balai", "🧹"),
    ("Le panier", "🧺"),
    ("Le rouleau de papier", "🧻"),
    ("L'éponge", "🧽"),
    ("Le pansement", "🩹"),
    ("Le stéthoscope", "🩺"),
    ("Le parachute", "🪂"),
    ("Le rasoir", "🪒"),
    ("La hache", "🪓"),
    ("La lampe à huile", "🪔"),
    ("Le banjo", "🪕"),
    ("L'échelle", "🪜"),
    ("Le miroir", "🪞"),
    # DE-only emojis:
    ("Le biscuit", "🍪"),
    ("Le ballon", "🎈"),
    ("La vache", "🐄"),
    ("La souris", "🐭"),
    ("Le t-shirt", "👕"),
    ("Le bébé", "👶"),
    ("Le livre", "📕"),
    # New emoji from EN fix: 🎨 arts, 🎋 bamboo, 🔆 bright, 🔅 dim, 🌍 globe, 🤝 mate, 🏔️ mountain, 🤼 wrestle
    ("La peinture", "🎨"),
    ("Le bambou", "🎋"),
    ("Lumineux", "🔆"),
    ("Sombre", "🔅"),
    ("Le globe terrestre", "🌍"),
    ("La poignée de main", "🤝"),
    ("La montagne enneigée", "🏔️"),
    ("La lutte", "🤼"),
    # FR-only emojis that need DE and EN already listed above for DE and EN
    # But FR already has these, so no need to add FR entries:
    # ⛪ L'église (already in FR), 🍟 Les frites (already in FR), 🎩 chapeau (already?)
    # Let me check: the analysis shows these ARE in FR but not DE/EN
    # So we don't add them to FR again
]


def fix_emoji_assignments(phrases: list) -> int:
    """Fix ❓ emoji assignments in the phrase list. Returns count of fixes."""
    fixed = 0
    for entry in phrases:
        phrase = entry.get("phrase", "")
        if phrase in EMOJI_FIXES and entry.get("emoji") == "❓":
            entry["emoji"] = EMOJI_FIXES[phrase]
            print(f"  fix emoji: '{phrase}' ❓ → {EMOJI_FIXES[phrase]}")
            fixed += 1
    return fixed


def add_phrases(phrases: list, new_entries: list, lang: str, category: str = "standard") -> int:
    """Add new phrases with espeak-ng IPA. Returns count of added entries."""
    existing_phrases = {e["phrase"] for e in phrases}
    existing_emojis_per_phrase = {e["phrase"]: e.get("emoji") for e in phrases}

    lang_code = {"de-DE": "de", "fr-FR": "fr", "en-GB": "en-gb"}[lang]
    added = 0

    for phrase, emoji in new_entries:
        if phrase in existing_phrases:
            # Phrase already exists — just check emoji is correct
            if existing_emojis_per_phrase.get(phrase) != emoji:
                print(f"  skip (exists, different emoji): '{phrase}'")
            else:
                pass  # Already exists with correct emoji
            continue

        # Generate IPA with espeak-ng
        ipa = get_espeak_ipa(phrase, lang_code)
        if not ipa:
            print(f"  warning: no IPA for '{phrase}' ({lang})")
            ipa = ""

        entry = {
            "phrase": phrase,
            "emoji": emoji,
            "ipas": [{"ipa": f"/{ipa}/" if ipa else "", "category": category}],
        }
        phrases.append(entry)
        existing_phrases.add(phrase)
        print(f"  + [{lang}] {phrase} ({emoji}) → /{ipa}/")
        added += 1

    return added


def main():
    de_path = REPO_ROOT / "phrases-de-DE.yaml"
    en_path = REPO_ROOT / "phrases-en-GB.yaml"
    fr_path = REPO_ROOT / "phrases-fr-FR.yaml"

    print("📖 Loading phrase files...")
    de = load_yaml(de_path)
    en = load_yaml(en_path)
    fr = load_yaml(fr_path)

    print(f"\n🔧 Fixing ❓ emoji assignments in phrases-en-GB.yaml...")
    fixed = fix_emoji_assignments(en)
    print(f"   → fixed {fixed} entries\n")

    print("🇩🇪 Adding German phrases...")
    n_de = add_phrases(de, NEW_DE, "de-DE")
    print(f"   → added {n_de} entries\n")

    print("🇬🇧 Adding English phrases...")
    n_en = add_phrases(en, NEW_EN, "en-GB")
    print(f"   → added {n_en} entries\n")

    print("🇫🇷 Adding French phrases...")
    n_fr = add_phrases(fr, NEW_FR, "fr-FR", category="vowels")
    print(f"   → added {n_fr} entries\n")

    print("💾 Saving files...")
    save_yaml(de_path, de)
    save_yaml(en_path, en)
    save_yaml(fr_path, fr)

    print("✅ Done!")
    print(f"\nSummary: fixed {fixed} EN emoji, added {n_de} DE, {n_en} EN, {n_fr} FR entries")
    print("Next steps:")
    print("  1. Run: ./run scripts/generate-phrase-audio.sh")
    print("  2. Run: ./run task deploy")


if __name__ == "__main__":
    main()
