#!/usr/bin/env tsx
/**
 * Compare IPA generated by different engines/methods against the reference IPA
 * stored in phrases-{lang}.yaml.
 *
 * Reads all files under static/ipa/{lang}/{engine}/{method}/{stem}.txt and prints
 * a table showing similarity (%) vs reference for each method.
 *
 * Usage: ./run tsx scripts/compare-ipa-engines.ts [lang] [--top N] [--min-sim S]
 *   lang:      optional, e.g. de-DE (defaults to all languages)
 *   --top N:   show only top N phrases per language (default: all)
 *   --min-sim S: only show rows where at least one method scores below S% (highlight disagreements)
 */

import fs from "fs";
import path from "path";
import yaml from "js-yaml";
import { calculatePanPhonDistance } from "../tests/panphon-distance-node.js";
import { PROJECT_ROOT, phraseToFilename, type PhraseEntry } from "./lib/phrase-audio-utils.js";

interface IpaFile {
  engine: string;
  method: string;
  stem: string;
  studyLang: string;
  ipa: string;
}

interface MethodKey {
  engine: string;
  method: string;
}

// ── Load all generated IPA files ─────────────────────────────────────────────

function loadAllIpaFiles(studyLang: string): IpaFile[] {
  const ipaRoot = path.join(PROJECT_ROOT, "static", "ipa", studyLang);
  if (!fs.existsSync(ipaRoot)) return [];

  const results: IpaFile[] = [];

  for (const engine of fs.readdirSync(ipaRoot)) {
    const engineDir = path.join(ipaRoot, engine);
    if (!fs.statSync(engineDir).isDirectory()) continue;

    for (const method of fs.readdirSync(engineDir)) {
      const methodDir = path.join(engineDir, method);
      if (!fs.statSync(methodDir).isDirectory()) continue;

      for (const file of fs.readdirSync(methodDir)) {
        if (!file.endsWith(".txt")) continue;
        const stem = file.replace(/\.txt$/, "");
        const ipa = fs.readFileSync(path.join(methodDir, file), "utf-8").trim();
        results.push({ engine, method, stem, studyLang, ipa });
      }
    }
  }

  return results;
}

// ── Load reference IPA from yaml ──────────────────────────────────────────────

interface RefEntry {
  phrase: string;
  refIpa: string;
}

function loadReferenceIpas(studyLang: string): Map<string, RefEntry> {
  const yamlPath = path.join(PROJECT_ROOT, `phrases-${studyLang}.yaml`);
  const entries = yaml.load(fs.readFileSync(yamlPath, "utf-8")) as PhraseEntry[];
  const map = new Map<string, RefEntry>();

  for (const entry of entries) {
    if (!entry.ipas || entry.ipas.length === 0) continue;
    const enGb = studyLang === "en-GB" ? entry.phrase : (entry["en-GB"] ?? entry.phrase);
    const stem = phraseToFilename(enGb);
    const refIpa = entry.ipas[0].ipa.replace(/^\/|\/$/g, "");
    map.set(stem, { phrase: entry.phrase, refIpa });
  }

  return map;
}

/** Load reference IPA from a generated engine/method directory instead of yaml. */
function loadReferenceIpasFromEngine(
  studyLang: string,
  refEngine: string,
  refMethod: string,
): Map<string, RefEntry> {
  // We still need phrase names — load from yaml for that
  const yamlPath = path.join(PROJECT_ROOT, `phrases-${studyLang}.yaml`);
  const entries = yaml.load(fs.readFileSync(yamlPath, "utf-8")) as PhraseEntry[];
  const refDir = path.join(PROJECT_ROOT, "static", "ipa", studyLang, refEngine, refMethod);
  const map = new Map<string, RefEntry>();

  for (const entry of entries) {
    const enGb = studyLang === "en-GB" ? entry.phrase : (entry["en-GB"] ?? entry.phrase);
    const stem = phraseToFilename(enGb);
    const refFile = path.join(refDir, `${stem}.txt`);
    if (!fs.existsSync(refFile)) continue;
    const refIpa = fs.readFileSync(refFile, "utf-8").trim();
    if (refIpa) map.set(stem, { phrase: entry.phrase, refIpa });
  }

  return map;
}

// ── Similarity helper ─────────────────────────────────────────────────────────

function similarity(ipa1: string, ipa2: string, studyLang: string): number {
  if (!ipa1 || !ipa2) return 0;
  try {
    return calculatePanPhonDistance(ipa1, ipa2, studyLang).similarity;
  } catch {
    return 0;
  }
}

// ── Main ─────────────────────────────────────────────────────────────────────

const LANGS = ["de-DE", "en-GB", "fr-FR", "it-IT"];

async function main(): Promise<void> {
  const rawArgs = process.argv.slice(2);
  let targetLang: string | undefined;
  let topN = Infinity;
  let minSimFilter = 0;
  let refEngine: string | undefined;
  let refMethod: string | undefined;

  if (rawArgs.includes("--help") || rawArgs.includes("-h")) {
    console.log(
      "Usage: ./run tsx scripts/compare-ipa-engines.ts [lang] [--top N] [--min-sim S] [--ref engine/method]",
    );
    console.log("");
    console.log("  lang         optional, e.g. de-DE (defaults to all languages)");
    console.log("  --top N      show only top N phrases per language (default: all)");
    console.log("  --min-sim S  only show rows where at least one method scores below S%");
    console.log("  --ref        reference engine/method, e.g. onnx-audio/edge-tts-male");
    process.exit(0);
  }

  for (let i = 0; i < rawArgs.length; i++) {
    if (rawArgs[i] === "--top") topN = parseInt(rawArgs[++i]);
    else if (rawArgs[i] === "--min-sim") minSimFilter = parseFloat(rawArgs[++i]) / 100;
    else if (rawArgs[i] === "--ref") {
      // e.g. --ref onnx-audio/edge-tts-male
      const parts = rawArgs[++i].split("/");
      refEngine = parts[0];
      refMethod = parts.slice(1).join("/");
    } else if (!rawArgs[i].startsWith("--")) targetLang = rawArgs[i];
  }

  const langs = targetLang ? [targetLang] : LANGS;

  for (const studyLang of langs) {
    const ipaFiles = loadAllIpaFiles(studyLang);
    if (ipaFiles.length === 0) {
      console.log(`\n[${studyLang}] No IPA files found — run generators first.`);
      continue;
    }

    const refs =
      refEngine && refMethod
        ? loadReferenceIpasFromEngine(studyLang, refEngine, refMethod)
        : loadReferenceIpas(studyLang);

    // Collect unique methods (engine/method pairs) in sorted order
    const methodSet = new Map<string, MethodKey>();
    for (const f of ipaFiles) {
      const key = `${f.engine}/${f.method}`;
      if (!methodSet.has(key)) methodSet.set(key, { engine: f.engine, method: f.method });
    }
    const methods = [...methodSet.values()].sort((a, b) =>
      `${a.engine}/${a.method}`.localeCompare(`${b.engine}/${b.method}`),
    );

    // Index: stem → method-key → ipa
    const index = new Map<string, Map<string, string>>();
    for (const f of ipaFiles) {
      if (!index.has(f.stem)) index.set(f.stem, new Map());
      index.get(f.stem)!.set(`${f.engine}/${f.method}`, f.ipa);
    }

    // Header
    const colWidth = 22;
    const pad = (s: string, n: number) => s.slice(0, n).padEnd(n);

    console.log(`\n${"═".repeat(120)}`);
    console.log(
      `[${studyLang}]  ${ipaFiles.length} IPA files, ${methods.length} methods, ${refs.size} reference phrases`,
    );
    console.log(`${"═".repeat(120)}`);

    const headerCols = ["phrase (ref IPA)", ...methods.map((m) => `${m.engine}/${m.method}`)];
    console.log(headerCols.map((h) => pad(h, colWidth)).join("  "));
    console.log("─".repeat(120));

    // Per-method running totals for average similarity
    const totals = new Map<string, { sum: number; n: number }>();
    for (const m of methods) totals.set(`${m.engine}/${m.method}`, { sum: 0, n: 0 });

    let shown = 0;

    for (const [stem, { phrase, refIpa }] of refs) {
      if (shown >= topN) break;

      const methodIpas = index.get(stem);
      if (!methodIpas) continue;

      // Compute similarities
      const sims = methods.map((m) => {
        const mKey = `${m.engine}/${m.method}`;
        const genIpa = methodIpas.get(mKey) ?? "";
        const sim = genIpa ? similarity(refIpa, genIpa, studyLang) : NaN;
        if (!isNaN(sim)) {
          const t = totals.get(mKey)!;
          t.sum += sim;
          t.n++;
        }
        return { mKey, genIpa, sim };
      });

      // Apply filter: skip if all methods score above minSimFilter
      if (minSimFilter > 0 && sims.every((s) => isNaN(s.sim) || s.sim >= minSimFilter)) continue;

      const refCol = `${phrase}  /${refIpa}/`;
      const cols = [pad(refCol, colWidth)];
      for (const { genIpa, sim } of sims) {
        const simStr = isNaN(sim) ? "—" : `${Math.round(sim * 100)}%`;
        cols.push(pad(`${genIpa.slice(0, 14)}  ${simStr}`, colWidth));
      }
      console.log(cols.join("  "));
      shown++;
    }

    // Per-method averages
    console.log("─".repeat(120));
    const avgRow = [pad("AVERAGE", colWidth)];
    for (const m of methods) {
      const { sum, n } = totals.get(`${m.engine}/${m.method}`)!;
      avgRow.push(pad(n > 0 ? `${Math.round((sum / n) * 100)}%  (n=${n})` : "—", colWidth));
    }
    console.log(avgRow.join("  "));
    console.log();
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
