#!/usr/bin/env python3
"""
Extract emojis with AoA (Age of Acquisition) below threshold.
Generates new-en.txt and new-de.txt with words suitable for language learning.

Usage:
    python scripts/extract_emoji_low_aoa.py --max-aoa 12
"""

import argparse
import sys
from pathlib import Path
from phrase_difficulty import PhraseDifficultyAnalyzer

# Add scripts directory to path to import existing tools
sys.path.insert(0, str(Path(__file__).parent))


# Comprehensive emoji-to-word mapping
# Using common emojis that are likely to have words with low AoA
EMOJI_WORD_MAP = {
    # Animals
    "🐱": "cat",
    "🐈": "cat",
    "🐶": "dog",
    "🐕": "dog",
    "🐭": "mouse",
    "🐹": "hamster",
    "🐰": "rabbit",
    "🦊": "fox",
    "🐻": "bear",
    "🐼": "panda",
    "🐨": "koala",
    "🐯": "tiger",
    "🦁": "lion",
    "🐮": "cow",
    "🐷": "pig",
    "🐸": "frog",
    "🐵": "monkey",
    "🦍": "gorilla",
    "🐔": "chicken",
    "🐧": "penguin",
    "🐦": "bird",
    "🐤": "chick",
    "🐣": "chick",
    "🐥": "chick",
    "🦆": "duck",
    "🦅": "eagle",
    "🦉": "owl",
    "🦇": "bat",
    "🐺": "wolf",
    "🐗": "boar",
    "🐴": "horse",
    "🦄": "unicorn",
    "🐝": "bee",
    "🐛": "caterpillar",
    "🦋": "butterfly",
    "🐌": "snail",
    "🐞": "ladybug",
    "🐜": "ant",
    "🦗": "cricket",
    "🕷️": "spider",
    "🦂": "scorpion",
    "🐢": "turtle",
    "🐍": "snake",
    "🦎": "lizard",
    "🦖": "dinosaur",
    "🐙": "octopus",
    "🦑": "squid",
    "🦀": "crab",
    "🐡": "fish",
    "🐠": "fish",
    "🐟": "fish",
    "🐬": "dolphin",
    "🦈": "shark",
    "🐳": "whale",
    "🐋": "whale",
    "🐊": "crocodile",
    "🐆": "leopard",
    "🐘": "elephant",
    "🦏": "rhino",
    "🦛": "hippo",
    "🐪": "camel",
    "🐫": "camel",
    "🦒": "giraffe",
    "🐃": "buffalo",
    "🐂": "ox",
    "🐄": "cow",
    "🐎": "horse",
    "🐖": "pig",
    "🐏": "ram",
    "🐑": "sheep",
    "🐐": "goat",
    "🦌": "deer",
    "🐕": "dog",
    "🐩": "poodle",
    "🐈": "cat",
    "🐓": "rooster",
    "🦃": "turkey",
    "🕊️": "dove",
    "🦚": "peacock",
    "🦜": "parrot",
    "🦢": "swan",
    "🦩": "flamingo",

    # Nature
    "🌳": "tree",
    "🌲": "tree",
    "🌴": "palm",
    "🌵": "cactus",
    "🌾": "wheat",
    "🌿": "herb",
    "☘️": "clover",
    "🍀": "clover",
    "🍁": "leaf",
    "🍂": "leaf",
    "🍃": "leaf",
    "🌸": "flower",
    "🌺": "flower",
    "🌻": "sunflower",
    "🌹": "rose",
    "🌷": "tulip",
    "🌼": "flower",
    "🌱": "seedling",
    "🌰": "chestnut",

    # Food & Drink
    "🍎": "apple",
    "🍏": "apple",
    "🍊": "orange",
    "🍋": "lemon",
    "🍌": "banana",
    "🍉": "watermelon",
    "🍇": "grapes",
    "🍓": "strawberry",
    "🍈": "melon",
    "🍒": "cherry",
    "🍑": "peach",
    "🥭": "mango",
    "🍍": "pineapple",
    "🥥": "coconut",
    "🥝": "kiwi",
    "🍅": "tomato",
    "🍆": "eggplant",
    "🥑": "avocado",
    "🥦": "broccoli",
    "🥬": "lettuce",
    "🥒": "cucumber",
    "🌶️": "pepper",
    "🌽": "corn",
    "🥕": "carrot",
    "🧄": "garlic",
    "🧅": "onion",
    "🥔": "potato",
    "🍠": "potato",
    "🥐": "croissant",
    "🥖": "bread",
    "🍞": "bread",
    "🥨": "pretzel",
    "🥯": "bagel",
    "🥞": "pancake",
    "🧇": "waffle",
    "🧀": "cheese",
    "🍖": "meat",
    "🍗": "chicken",
    "🥩": "steak",
    "🥓": "bacon",
    "🍔": "burger",
    "🍟": "fries",
    "🍕": "pizza",
    "🌭": "hotdog",
    "🥪": "sandwich",
    "🌮": "taco",
    "🌯": "burrito",
    "🥗": "salad",
    "🥘": "paella",
    "🍝": "pasta",
    "🍜": "noodle",
    "🍲": "stew",
    "🍛": "curry",
    "🍣": "sushi",
    "🍱": "bento",
    "🥟": "dumpling",
    "🍤": "shrimp",
    "🍙": "rice",
    "🍚": "rice",
    "🍘": "rice",
    "🍥": "fishcake",
    "🥠": "cookie",
    "🥮": "mooncake",
    "🍢": "oden",
    "🍡": "dango",
    "🍧": "ice",
    "🍨": "ice",
    "🍦": "ice",
    "🥧": "pie",
    "🧁": "cupcake",
    "🍰": "cake",
    "🎂": "cake",
    "🍮": "pudding",
    "🍭": "candy",
    "🍬": "candy",
    "🍫": "chocolate",
    "🍿": "popcorn",
    "🍩": "donut",
    "🍪": "cookie",
    "🌰": "chestnut",
    "🥜": "peanut",
    "🍯": "honey",
    "🥛": "milk",
    "🍼": "bottle",
    "☕": "coffee",
    "🫖": "tea",
    "🍵": "tea",
    "🍶": "sake",
    "🍾": "champagne",
    "🍷": "wine",
    "🍸": "cocktail",
    "🍹": "juice",
    "🍺": "beer",
    "🍻": "beer",
    "🥂": "champagne",
    "🥃": "whiskey",
    "🥤": "soda",
    "🧃": "juice",
    "🧉": "mate",
    "🧊": "ice",

    # Weather & Sky
    "☀️": "sun",
    "🌤️": "sun",
    "⛅": "cloud",
    "☁️": "cloud",
    "🌥️": "cloud",
    "🌦️": "rain",
    "🌧️": "rain",
    "⛈️": "storm",
    "🌩️": "lightning",
    "🌨️": "snow",
    "❄️": "snow",
    "☃️": "snowman",
    "⛄": "snowman",
    "🌬️": "wind",
    "💨": "wind",
    "🌪️": "tornado",
    "🌫️": "fog",
    "🌈": "rainbow",
    "🌙": "moon",
    "🌚": "moon",
    "🌛": "moon",
    "🌜": "moon",
    "🌝": "moon",
    "⭐": "star",
    "🌟": "star",
    "✨": "sparkle",
    "💫": "dizzy",
    "☄️": "comet",

    # Objects & Buildings
    "🏠": "house",
    "🏡": "house",
    "🏘️": "houses",
    "🏚️": "house",
    "🏗️": "building",
    "🏭": "factory",
    "🏢": "office",
    "🏬": "store",
    "🏣": "post",
    "🏤": "post",
    "🏥": "hospital",
    "🏦": "bank",
    "🏨": "hotel",
    "🏪": "store",
    "🏫": "school",
    "🏩": "hotel",
    "💒": "church",
    "🏛️": "museum",
    "⛪": "church",
    "🕌": "mosque",
    "🛕": "temple",
    "🕍": "synagogue",
    "⛩️": "shrine",
    "🗾": "japan",
    "🎠": "carousel",
    "🎡": "wheel",
    "🎢": "coaster",
    "💈": "barber",
    "🎪": "circus",

    # Vehicles
    "🚗": "car",
    "🚕": "taxi",
    "🚙": "car",
    "🚌": "bus",
    "🚎": "bus",
    "🏎️": "car",
    "🚓": "police",
    "🚑": "ambulance",
    "🚒": "truck",
    "🚐": "van",
    "🚚": "truck",
    "🚛": "truck",
    "🚜": "tractor",
    "🦯": "cane",
    "🦽": "wheelchair",
    "🦼": "wheelchair",
    "🛴": "scooter",
    "🚲": "bicycle",
    "🛵": "scooter",
    "🏍️": "motorcycle",
    "🛺": "rickshaw",
    "🚨": "siren",
    "🚔": "police",
    "🚍": "bus",
    "🚘": "car",
    "🚖": "taxi",
    "🚡": "cable",
    "🚠": "cable",
    "🚟": "monorail",
    "🚃": "train",
    "🚋": "tram",
    "🚞": "train",
    "🚝": "monorail",
    "🚄": "train",
    "🚅": "train",
    "🚈": "train",
    "🚂": "train",
    "🚆": "train",
    "🚇": "metro",
    "🚊": "tram",
    "🚉": "station",
    "✈️": "airplane",
    "🛫": "airplane",
    "🛬": "airplane",
    "🛩️": "airplane",
    "💺": "seat",
    "🚁": "helicopter",
    "🚟": "monorail",
    "🚠": "cable",
    "🚡": "cable",
    "🛰️": "satellite",
    "🚀": "rocket",
    "🛸": "ufo",
    "🛶": "canoe",
    "⛵": "sailboat",
    "🚤": "boat",
    "🛥️": "boat",
    "🛳️": "ship",
    "⛴️": "ferry",
    "🚢": "ship",
    "⚓": "anchor",
    "⛽": "fuel",
    "🚧": "construction",
    "🚦": "light",
    "🚥": "light",
    "🚏": "stop",
    "🗺️": "map",
    "🗿": "statue",
    "🗼": "tower",
    "🗽": "liberty",
    "⛲": "fountain",
    "⛱️": "umbrella",
    "🏖️": "beach",
    "🏝️": "island",

    # Activities & Sports
    "⚽": "ball",
    "🏀": "basketball",
    "🏈": "football",
    "⚾": "baseball",
    "🥎": "softball",
    "🎾": "tennis",
    "🏐": "volleyball",
    "🏉": "rugby",
    "🥏": "frisbee",
    "🎱": "pool",
    "🪀": "yoyo",
    "🏓": "ping",
    "🏸": "badminton",
    "🏒": "hockey",
    "🏑": "hockey",
    "🥍": "lacrosse",
    "🏏": "cricket",
    "🥅": "goal",
    "⛳": "golf",
    "🏹": "archery",
    "🎣": "fishing",
    "🤿": "diving",
    "🥊": "boxing",
    "🥋": "martial",
    "🎽": "shirt",
    "🛹": "skateboard",
    "🛼": "skate",
    "⛸️": "skate",
    "🥌": "curling",
    "🎿": "ski",
    "⛷️": "ski",
    "🏂": "snowboard",
    "🪂": "parachute",
    "🏋️": "weight",
    "🤼": "wrestling",
    "🤸": "cartwheel",
    "🤺": "fencing",
    "🤾": "handball",
    "🏌️": "golf",
    "🏇": "horse",
    "🧘": "yoga",
    "🏊": "swim",
    "🏄": "surf",
    "🚣": "row",
    "🧗": "climb",
    "🚴": "bike",
    "🚵": "bike",
    "🤹": "juggle",

    # Objects & Tools
    "⌚": "watch",
    "📱": "phone",
    "📲": "phone",
    "💻": "computer",
    "⌨️": "keyboard",
    "🖥️": "computer",
    "🖨️": "printer",
    "🖱️": "mouse",
    "🖲️": "trackball",
    "🕹️": "joystick",
    "🗜️": "clamp",
    "💾": "disk",
    "💿": "cd",
    "📀": "dvd",
    "📼": "tape",
    "📷": "camera",
    "📸": "camera",
    "📹": "video",
    "🎥": "camera",
    "📽️": "projector",
    "🎞️": "film",
    "📞": "phone",
    "☎️": "phone",
    "📟": "pager",
    "📠": "fax",
    "📺": "tv",
    "📻": "radio",
    "🎙️": "microphone",
    "🎚️": "slider",
    "🎛️": "knobs",
    "🧭": "compass",
    "⏱️": "stopwatch",
    "⏲️": "timer",
    "⏰": "clock",
    "🕰️": "clock",
    "⌛": "hourglass",
    "⏳": "hourglass",
    "📡": "satellite",
    "🔋": "battery",
    "🔌": "plug",
    "💡": "bulb",
    "🔦": "flashlight",
    "🕯️": "candle",
    "🪔": "lamp",
    "🧯": "extinguisher",
    "🛢️": "drum",
    "💸": "money",
    "💵": "dollar",
    "💴": "yen",
    "💶": "euro",
    "💷": "pound",
    "💰": "money",
    "💳": "card",
    "💎": "gem",
    "⚖️": "scale",
    "🧰": "toolbox",
    "🔧": "wrench",
    "🔨": "hammer",
    "⚒️": "hammer",
    "🛠️": "tools",
    "⛏️": "pick",
    "🔩": "bolt",
    "⚙️": "gear",
    "🧱": "brick",
    "⛓️": "chain",
    "🧲": "magnet",
    "🔫": "gun",
    "💣": "bomb",
    "🧨": "firecracker",
    "🪓": "axe",
    "🔪": "knife",
    "🗡️": "sword",
    "⚔️": "swords",
    "🛡️": "shield",
    "🚬": "cigarette",
    "⚰️": "coffin",
    "⚱️": "urn",
    "🏺": "amphora",
    "🔮": "ball",
    "📿": "beads",
    "💈": "barber",
    "⚗️": "alembic",
    "🔭": "telescope",
    "🔬": "microscope",
    "🕳️": "hole",
    "💊": "pill",
    "💉": "syringe",
    "🩹": "bandage",
    "🩺": "stethoscope",
    "🚪": "door",
    "🛗": "elevator",
    "🪞": "mirror",
    "🪟": "window",
    "🛏️": "bed",
    "🛋️": "couch",
    "🪑": "chair",
    "🚽": "toilet",
    "🚿": "shower",
    "🛁": "bathtub",
    "🪒": "razor",
    "🧴": "lotion",
    "🧷": "pin",
    "🧹": "broom",
    "🧺": "basket",
    "🧻": "paper",
    "🧼": "soap",
    "🧽": "sponge",
    "🧯": "extinguisher",
    "🛒": "cart",

    # Clothes & Accessories
    "👓": "glasses",
    "🕶️": "sunglasses",
    "🥽": "goggles",
    "🥼": "coat",
    "🦺": "vest",
    "👔": "tie",
    "👕": "shirt",
    "👖": "jeans",
    "🧣": "scarf",
    "🧤": "gloves",
    "🧥": "coat",
    "🧦": "socks",
    "👗": "dress",
    "👘": "kimono",
    "🥻": "sari",
    "🩱": "swimsuit",
    "🩲": "underwear",
    "🩳": "shorts",
    "👙": "bikini",
    "👚": "shirt",
    "👛": "purse",
    "👜": "bag",
    "👝": "clutch",
    "🛍️": "bag",
    "🎒": "backpack",
    "👞": "shoe",
    "👟": "shoe",
    "🥾": "boot",
    "🥿": "shoe",
    "👠": "heel",
    "👡": "sandal",
    "🩰": "shoe",
    "👢": "boot",
    "👑": "crown",
    "👒": "hat",
    "🎩": "hat",
    "🎓": "cap",
    "🧢": "cap",
    "⛑️": "helmet",
    "💄": "lipstick",
    "💍": "ring",
    "💼": "briefcase",

    # Symbols & Icons
    "❤️": "heart",
    "🧡": "heart",
    "💛": "heart",
    "💚": "heart",
    "💙": "heart",
    "💜": "heart",
    "🖤": "heart",
    "🤍": "heart",
    "🤎": "heart",
    "💔": "heart",
    "❣️": "heart",
    "💕": "hearts",
    "💞": "hearts",
    "💓": "heart",
    "💗": "heart",
    "💖": "heart",
    "💘": "heart",
    "💝": "heart",
    "💟": "heart",
    "☮️": "peace",
    "✝️": "cross",
    "☪️": "crescent",
    "🕉️": "om",
    "☸️": "wheel",
    "✡️": "star",
    "🔯": "star",
    "🕎": "menorah",
    "☯️": "yin",
    "☦️": "cross",
    "🛐": "worship",
    "⛎": "ophiuchus",
    "♈": "aries",
    "♉": "taurus",
    "♊": "gemini",
    "♋": "cancer",
    "♌": "leo",
    "♍": "virgo",
    "♎": "libra",
    "♏": "scorpio",
    "♐": "sagittarius",
    "♑": "capricorn",
    "♒": "aquarius",
    "♓": "pisces",
    "🆔": "id",
    "⚛️": "atom",
    "🉑": "accept",
    "☢️": "radioactive",
    "☣️": "biohazard",
    "📴": "off",
    "📳": "vibrate",
    "🆚": "vs",
    "💮": "flower",
    "🉐": "bargain",
    "㊙️": "secret",
    "㊗️": "congratulations",
    "🈴": "pass",
    "🈵": "full",
    "🈹": "discount",
    "🈲": "prohibit",
    "🅰️": "a",
    "🅱️": "b",
    "🆎": "ab",
    "🆑": "cl",
    "🅾️": "o",
    "🆘": "sos",
    "⭕": "circle",
    "🛑": "stop",
    "⛔": "entry",
    "📛": "name",
    "🚫": "prohibited",
    "💯": "hundred",
    "💢": "anger",
    "♨️": "hot",
    "🚷": "pedestrian",
    "🚯": "litter",
    "🚳": "bicycle",
    "🚱": "water",
    "🔞": "underage",
    "📵": "phone",
    "🚭": "smoking",
    "❗": "exclamation",
    "❕": "exclamation",
    "❓": "question",
    "❔": "question",
    "‼️": "exclamation",
    "⁉️": "question",
    "🔅": "dim",
    "🔆": "bright",
    "〽️": "wavy",
    "⚠️": "warning",
    "🚸": "children",
    "🔱": "trident",
    "⚜️": "fleur",
    "🔰": "beginner",
    "♻️": "recycle",
    "✅": "check",
    "🈯": "reserved",
    "💹": "chart",
    "❇️": "sparkle",
    "✳️": "asterisk",
    "❎": "cross",
    "🌐": "globe",
    "💠": "diamond",
    "Ⓜ️": "m",
    "🌀": "cyclone",
    "💤": "sleep",
    "🏧": "atm",
    "🚾": "wc",
    "♿": "wheelchair",
    "🅿️": "parking",
    "🈳": "vacancy",
    "🈂️": "service",
    "🛂": "passport",
    "🛃": "customs",
    "🛄": "baggage",
    "🛅": "luggage",
    "🚹": "men",
    "🚺": "women",
    "🚼": "baby",
    "🚻": "restroom",
    "🚮": "litter",
    "🎦": "cinema",
    "📶": "signal",
    "🈁": "here",
    "🔣": "symbols",
    "ℹ️": "information",
    "🔤": "abc",
    "🔡": "abcd",
    "🔠": "capital",
    "🆖": "ng",
    "🆗": "ok",
    "🆙": "up",
    "🆒": "cool",
    "🆕": "new",
    "🆓": "free",
    "0️⃣": "zero",
    "1️⃣": "one",
    "2️⃣": "two",
    "3️⃣": "three",
    "4️⃣": "four",
    "5️⃣": "five",
    "6️⃣": "six",
    "7️⃣": "seven",
    "8️⃣": "eight",
    "9️⃣": "nine",
    "🔟": "ten",

    # Body parts
    "👁️": "eye",
    "👀": "eyes",
    "👂": "ear",
    "👃": "nose",
    "👄": "mouth",
    "👅": "tongue",
    "🦷": "tooth",
    "🦴": "bone",
    "👶": "baby",
    "🧒": "child",
    "👦": "boy",
    "👧": "girl",
    "🧑": "person",
    "👨": "man",
    "👩": "woman",
    "🧓": "older",
    "👴": "man",
    "👵": "woman",
    "🙍": "frown",
    "🙎": "pout",
    "🙅": "no",
    "🙆": "ok",
    "💁": "information",
    "🙋": "raise",
    "🧏": "deaf",
    "🙇": "bow",
    "🤦": "facepalm",
    "🤷": "shrug",
    "👮": "police",
    "🕵️": "detective",
    "💂": "guard",
    "👷": "construction",
    "🤴": "prince",
    "👸": "princess",
    "👳": "turban",
    "👲": "cap",
    "🧕": "headscarf",
    "🤵": "tuxedo",
    "👰": "bride",
    "🤰": "pregnant",
    "🤱": "feeding",
    "👼": "angel",
    "🎅": "santa",
    "🤶": "santa",
    "🦸": "superhero",
    "🦹": "supervillain",
    "🧙": "mage",
    "🧚": "fairy",
    "🧛": "vampire",
    "🧜": "merperson",
    "🧝": "elf",
    "🧞": "genie",
    "🧟": "zombie",
    "💆": "massage",
    "💇": "haircut",
    "🚶": "walk",
    "🧍": "stand",
    "🧎": "kneel",
    "👨‍🦯": "blind",
    "👨‍🦼": "wheelchair",
    "👨‍🦽": "wheelchair",
    "🏃": "run",
    "💃": "dance",
    "🕺": "dance",
    "🕴️": "suit",
    "👯": "bunny",
    "🧖": "sauna",
    "🧗": "climb",
    "🤺": "fence",
    "🏇": "horse",
    "⛷️": "ski",
    "🏂": "snowboard",
    "🏌️": "golf",
    "🏄": "surf",
    "🚣": "row",
    "🏊": "swim",
    "⛹️": "ball",
    "🏋️": "lift",
    "🚴": "bike",
    "🚵": "mountain",
    "🤸": "cartwheel",
    "🤼": "wrestle",
    "🤽": "polo",
    "🤾": "handball",
    "🤹": "juggle",
    "🧘": "lotus",
    "🛀": "bath",
    "🛌": "sleep",
    "👭": "women",
    "👫": "couple",
    "👬": "men",
    "💏": "kiss",
    "💑": "couple",
    "👪": "family",
    "🗣️": "speak",
    "👤": "bust",
    "👥": "busts",
    "👣": "footprints",

    # Hand gestures
    "🤲": "hands",
    "👐": "hands",
    "🙌": "hands",
    "👏": "clap",
    "🤝": "handshake",
    "👍": "thumbs",
    "👎": "thumbs",
    "👊": "fist",
    "✊": "fist",
    "🤛": "fist",
    "🤜": "fist",
    "🤞": "fingers",
    "✌️": "victory",
    "🤟": "love",
    "🤘": "rock",
    "👌": "ok",
    "🤏": "pinch",
    "👈": "left",
    "👉": "right",
    "👆": "up",
    "👇": "down",
    "☝️": "up",
    "✋": "hand",
    "🤚": "hand",
    "🖐️": "hand",
    "🖖": "spock",
    "👋": "wave",
    "🤙": "call",
    "💪": "muscle",
    "🦾": "arm",
    "🖕": "finger",
    "✍️": "write",
    "🙏": "pray",
    "🦶": "foot",
    "🦵": "leg",
    "🦿": "leg",

    # Household items
    "🪑": "chair",
    "🛏️": "bed",
    "🛋️": "sofa",
    "🪞": "mirror",
    "🪟": "window",
    "🚪": "door",
    "🪜": "ladder",
    "🧺": "basket",
    "🧻": "paper",
    "🧼": "soap",
    "🧽": "sponge",
    "🧴": "bottle",
    "🧹": "broom",
    "🧷": "pin",
    "🪠": "plunger",
    "🪣": "bucket",
    "🧯": "fire",
    "🛒": "cart",

    # Office & School
    "✏️": "pencil",
    "✒️": "pen",
    "🖋️": "pen",
    "🖊️": "pen",
    "🖌️": "brush",
    "🖍️": "crayon",
    "📝": "memo",
    "💼": "briefcase",
    "📁": "folder",
    "📂": "folder",
    "🗂️": "dividers",
    "📅": "calendar",
    "📆": "calendar",
    "🗒️": "notepad",
    "🗓️": "calendar",
    "📇": "cards",
    "📈": "chart",
    "📉": "chart",
    "📊": "chart",
    "📋": "clipboard",
    "📌": "pin",
    "📍": "pin",
    "📎": "clip",
    "🖇️": "clips",
    "📏": "ruler",
    "📐": "triangle",
    "✂️": "scissors",
    "🗃️": "box",
    "🗄️": "cabinet",
    "🗑️": "trash",
    "🔒": "lock",
    "🔓": "unlock",
    "🔏": "lock",
    "🔐": "lock",
    "🔑": "key",
    "🗝️": "key",

    # Books & Learning
    "📕": "book",
    "📗": "book",
    "📘": "book",
    "📙": "book",
    "📔": "notebook",
    "📓": "notebook",
    "📒": "ledger",
    "📃": "page",
    "📜": "scroll",
    "📄": "paper",
    "📰": "newspaper",
    "🗞️": "newspaper",
    "📑": "bookmark",
    "🔖": "bookmark",
    "🏷️": "label",
    "💰": "bag",
    "💴": "yen",
    "💵": "dollar",
    "💶": "euro",
    "💷": "pound",
    "💸": "money",
    "💳": "card",
    "🧾": "receipt",
    "💹": "chart",

    # Music & Entertainment
    "🎼": "score",
    "🎵": "note",
    "🎶": "notes",
    "🎙️": "microphone",
    "🎚️": "slider",
    "🎛️": "knobs",
    "🎤": "microphone",
    "🎧": "headphone",
    "📻": "radio",
    "🎷": "saxophone",
    "🎸": "guitar",
    "🎹": "keyboard",
    "🎺": "trumpet",
    "🎻": "violin",
    "🪕": "banjo",
    "🥁": "drum",
    "🎬": "clapper",
    "🎭": "arts",
    "🎪": "circus",
    "🎨": "palette",
    "🎰": "slot",
    "🎲": "dice",
    "🎯": "dart",
    "🎳": "bowling",
    "🎮": "game",
    "🎴": "cards",
    "🃏": "joker",
    "🀄": "mahjong",
    "🎁": "gift",
    "🎀": "ribbon",
    "🎈": "balloon",
    "🎉": "party",
    "🎊": "confetti",
    "🎋": "tanabata",
    "🎍": "bamboo",
    "🎎": "dolls",
    "🎏": "carp",
    "🎐": "chime",
    "🧧": "envelope",

    # Time
    "🕐": "clock",
    "🕑": "clock",
    "🕒": "clock",
    "🕓": "clock",
    "🕔": "clock",
    "🕕": "clock",
    "🕖": "clock",
    "🕗": "clock",
    "🕘": "clock",
    "🕙": "clock",
    "🕚": "clock",
    "🕛": "clock",
}


# German articles database (simplified)
# Maps English words to German with articles
GERMAN_ARTICLES = {
    "cat": ("Katze", "die"),
    "dog": ("Hund", "der"),
    "mouse": ("Maus", "die"),
    "hamster": ("Hamster", "der"),
    "rabbit": ("Kaninchen", "das"),
    "fox": ("Fuchs", "der"),
    "bear": ("Bär", "der"),
    "panda": ("Panda", "der"),
    "tiger": ("Tiger", "der"),
    "lion": ("Löwe", "der"),
    "cow": ("Kuh", "die"),
    "pig": ("Schwein", "das"),
    "frog": ("Frosch", "der"),
    "monkey": ("Affe", "der"),
    "chicken": ("Huhn", "das"),
    "penguin": ("Pinguin", "der"),
    "bird": ("Vogel", "der"),
    "chick": ("Küken", "das"),
    "duck": ("Ente", "die"),
    "eagle": ("Adler", "der"),
    "owl": ("Eule", "die"),
    "bat": ("Fledermaus", "die"),
    "wolf": ("Wolf", "der"),
    "horse": ("Pferd", "das"),
    "bee": ("Biene", "die"),
    "butterfly": ("Schmetterling", "der"),
    "snail": ("Schnecke", "die"),
    "ant": ("Ameise", "die"),
    "spider": ("Spinne", "die"),
    "turtle": ("Schildkröte", "die"),
    "snake": ("Schlange", "die"),
    "fish": ("Fisch", "der"),
    "dolphin": ("Delfin", "der"),
    "whale": ("Wal", "der"),
    "elephant": ("Elefant", "der"),
    "giraffe": ("Giraffe", "die"),
    "sheep": ("Schaf", "das"),
    "goat": ("Ziege", "die"),
    "deer": ("Reh", "das"),
    "rooster": ("Hahn", "der"),
    "tree": ("Baum", "der"),
    "flower": ("Blume", "die"),
    "rose": ("Rose", "die"),
    "leaf": ("Blatt", "das"),
    "apple": ("Apfel", "der"),
    "orange": ("Orange", "die"),
    "lemon": ("Zitrone", "die"),
    "banana": ("Banane", "die"),
    "watermelon": ("Wassermelone", "die"),
    "grapes": ("Trauben", "die"),
    "strawberry": ("Erdbeere", "die"),
    "cherry": ("Kirsche", "die"),
    "tomato": ("Tomate", "die"),
    "carrot": ("Karotte", "die"),
    "potato": ("Kartoffel", "die"),
    "bread": ("Brot", "das"),
    "cheese": ("Käse", "der"),
    "meat": ("Fleisch", "das"),
    "burger": ("Burger", "der"),
    "pizza": ("Pizza", "die"),
    "cake": ("Kuchen", "der"),
    "candy": ("Bonbon", "das"),
    "chocolate": ("Schokolade", "die"),
    "cookie": ("Keks", "der"),
    "milk": ("Milch", "die"),
    "water": ("Wasser", "das"),
    "coffee": ("Kaffee", "der"),
    "tea": ("Tee", "der"),
    "juice": ("Saft", "der"),
    "beer": ("Bier", "das"),
    "sun": ("Sonne", "die"),
    "cloud": ("Wolke", "die"),
    "rain": ("Regen", "der"),
    "snow": ("Schnee", "der"),
    "wind": ("Wind", "der"),
    "rainbow": ("Regenbogen", "der"),
    "moon": ("Mond", "der"),
    "star": ("Stern", "der"),
    "house": ("Haus", "das"),
    "building": ("Gebäude", "das"),
    "school": ("Schule", "die"),
    "hospital": ("Krankenhaus", "das"),
    "church": ("Kirche", "die"),
    "car": ("Auto", "das"),
    "bus": ("Bus", "der"),
    "train": ("Zug", "der"),
    "bicycle": ("Fahrrad", "das"),
    "airplane": ("Flugzeug", "das"),
    "boat": ("Boot", "das"),
    "ship": ("Schiff", "das"),
    "ball": ("Ball", "der"),
    "watch": ("Uhr", "die"),
    "phone": ("Telefon", "das"),
    "computer": ("Computer", "der"),
    "camera": ("Kamera", "die"),
    "tv": ("Fernseher", "der"),
    "clock": ("Uhr", "die"),
    "money": ("Geld", "das"),
    "hammer": ("Hammer", "der"),
    "knife": ("Messer", "das"),
    "door": ("Tür", "die"),
    "window": ("Fenster", "das"),
    "bed": ("Bett", "das"),
    "chair": ("Stuhl", "der"),
    "table": ("Tisch", "der"),
    "glasses": ("Brille", "die"),
    "shirt": ("Hemd", "das"),
    "pants": ("Hose", "die"),
    "dress": ("Kleid", "das"),
    "shoe": ("Schuh", "der"),
    "hat": ("Hut", "der"),
    "heart": ("Herz", "das"),
    "hand": ("Hand", "die"),
    "foot": ("Fuß", "der"),
    "eye": ("Auge", "das"),
    "ear": ("Ohr", "das"),
    "nose": ("Nase", "die"),
    "mouth": ("Mund", "der"),
    "tooth": ("Zahn", "der"),
    "baby": ("Baby", "das"),
    "child": ("Kind", "das"),
    "boy": ("Junge", "der"),
    "girl": ("Mädchen", "das"),
    "man": ("Mann", "der"),
    "woman": ("Frau", "die"),
    "book": ("Buch", "das"),
    "pen": ("Stift", "der"),
    "pencil": ("Bleistift", "der"),
    "paper": ("Papier", "das"),
    "key": ("Schlüssel", "der"),
    "gift": ("Geschenk", "das"),
    "balloon": ("Ballon", "der"),
    "flag": ("Flagge", "die"),
}


def main():
    parser = argparse.ArgumentParser(
        description="Extract emojis with low AoA for language learning"
    )
    parser.add_argument(
        "--max-aoa",
        type=float,
        default=12.0,
        help="Maximum Age of Acquisition threshold (default: 12 years)"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("."),
        help="Output directory for generated files (default: current directory)"
    )

    args = parser.parse_args()

    print("=" * 70)
    print("Emoji AoA Extraction Tool")
    print("=" * 70)
    print(f"Maximum AoA threshold: {args.max_aoa} years")
    print(f"Output directory: {args.output_dir}")
    print()

    # Initialize analyzer
    print("Initializing phrase difficulty analyzer...")
    analyzer = PhraseDifficultyAnalyzer()
    print()

    # Process emojis
    english_words = set()
    german_words = set()
    emoji_results = []

    total_emojis = len(EMOJI_WORD_MAP)
    print(f"Processing {total_emojis} emojis...")
    print()

    for i, (emoji, english_word) in enumerate(EMOJI_WORD_MAP.items(), 1):
        if i % 50 == 0:
            print(f"  Progress: {i}/{total_emojis} emojis processed...")

        # Check AoA for English word
        aoa = analyzer.get_aoa(english_word, use_adult_fallback=False)

        if aoa is not None and aoa < args.max_aoa:
            english_words.add(english_word)
            emoji_results.append({
                "emoji": emoji,
                "english": english_word,
                "aoa": aoa
            })

            # Get German translation if available
            if english_word in GERMAN_ARTICLES:
                german_word, article = GERMAN_ARTICLES[english_word]
                german_words.add(german_word)
                german_words.add(f"{article.capitalize()} {german_word}")

    print()
    print("=" * 70)
    print(f"Found {len(emoji_results)} emojis with AoA < {args.max_aoa} years")
    print(f"  English words: {len(english_words)}")
    print(f"  German words: {len(german_words)}")
    print("=" * 70)
    print()

    # Sort results by AoA
    emoji_results.sort(key=lambda x: x["aoa"])

    # Write English words
    en_file = args.output_dir / "new-en.txt"
    with open(en_file, "w", encoding="utf-8") as f:
        for word in sorted(english_words):
            f.write(f"{word}\n")
    print(f"✅ Wrote {len(english_words)} English words to {en_file}")

    # Write German words
    de_file = args.output_dir / "new-de.txt"
    with open(de_file, "w", encoding="utf-8") as f:
        for word in sorted(german_words):
            f.write(f"{word}\n")
    print(f"✅ Wrote {len(german_words)} German words to {de_file}")

    # Write detailed report
    report_file = args.output_dir / "emoji-aoa-report.txt"
    with open(report_file, "w", encoding="utf-8") as f:
        f.write("=" * 70 + "\n")
        f.write(f"Emoji AoA Report (threshold: {args.max_aoa} years)\n")
        f.write("=" * 70 + "\n\n")

        for result in emoji_results:
            emoji = result["emoji"]
            english = result["english"]
            aoa = result["aoa"]

            f.write(f"{emoji}  {english:20s}  AoA: {aoa:4.1f} years\n")

            # Add German if available
            if english in GERMAN_ARTICLES:
                german_word, article = GERMAN_ARTICLES[english]
                f.write(f"     → German: {german_word} ({article.capitalize()} {german_word})\n")
            f.write("\n")

    print(f"✅ Wrote detailed report to {report_file}")
    print()
    print("Next steps:")
    print("  1. Review the generated files")
    print("  2. Run the import script to add phrases to the YAML files")
    print()


if __name__ == "__main__":
    main()
