#!/usr/bin/env bash
# Generate SCRIPTS.md by calling every script in scripts/ with --help in parallel.
# Usage: ./scripts/generate-scripts-md.sh

if [[ "${1:-}" == "--help" ]] || [[ "${1:-}" == "-h" ]]; then
    echo "Usage: ./scripts/generate-scripts-md.sh"
    echo ""
    echo "Generate SCRIPTS.md by calling each script in scripts/ with --help in parallel."
    echo "Called by Taskfile as part of the 'docs' task."
    exit 0
fi

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT="$PROJECT_DIR/SCRIPTS.md"

cd "$PROJECT_DIR"

TMPDIR_WORK="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_WORK"' EXIT

# Get --help output for one script and write to a temp file.
help_for_script() {
    local script="$1"
    local name
    name="$(basename "$script")"
    local out

    if [[ "$script" == *.ts ]]; then
        out="$(tsx "$script" --help 2>&1)" || out="(no --help output)"
    elif [[ "$script" == *.py ]]; then
        out="$(python3 "$script" --help 2>&1)" || out="(no --help output)"
    elif [[ "$script" == *.sh ]]; then
        out="$(bash "$script" --help 2>&1)" || out="(no --help output)"
    else
        return
    fi

    # Strip absolute project path from help output
    out="${out//$PROJECT_DIR\//./}"

    printf '## %s\n\n```\n%s\n```\n\n' "$name" "$out" > "$TMPDIR_WORK/$name.md"
}

export -f help_for_script
export TMPDIR_WORK

# Collect all scripts (sorted, excluding this script itself)
mapfile -t scripts < <(
    find "$SCRIPT_DIR" -maxdepth 1 \( -name "*.ts" -o -name "*.py" -o -name "*.sh" \) \
        ! -name "generate-scripts-md.sh" \
        | sort
)

# Run all --help calls in parallel
for script in "${scripts[@]}"; do
    help_for_script "$script" &
done
wait

# Assemble SCRIPTS.md in sorted order
{
    echo "# Scripts"
    echo ""
    echo "<!-- Auto-generated by \`scripts/generate-scripts-md.sh\`. Do not edit manually. -->"
    echo ""
    for script in "${scripts[@]}"; do
        name="$(basename "$script")"
        if [[ -f "$TMPDIR_WORK/$name.md" ]]; then
            cat "$TMPDIR_WORK/$name.md"
        fi
    done
} > "$OUTPUT"

echo "Generated $OUTPUT ($(wc -l < "$OUTPUT") lines, ${#scripts[@]} scripts)"
