#!/usr/bin/env python3
"""
Import new phrases from a text file into phrases-{lang}.yaml

Features:
- Reads phrases from a text file (one per line)
- Finds matching emoji from the emoji database
- Avoids duplicates
- Adds phrases to the YAML file
- Automatically runs update-ipa.ts and update-difficulty.py

Usage:
    python scripts/import_phrases.py new-en.txt phrases-en-GB.yaml
    python scripts/import_phrases.py new-de.txt phrases-de-DE.yaml
"""

import argparse
import sys
import subprocess
from pathlib import Path
import yaml


# Inverted emoji map for looking up emojis by word
# This is derived from the EMOJI_WORD_MAP in extract_emoji_low_aoa.py
WORD_TO_EMOJI = {
    "cat": "🐱",
    "dog": "🐶",
    "mouse": "🐭",
    "hamster": "🐹",
    "rabbit": "🐰",
    "fox": "🦊",
    "bear": "🐻",
    "panda": "🐼",
    "koala": "🐨",
    "tiger": "🦁",
    "lion": "🦁",
    "cow": "🐮",
    "pig": "🐷",
    "frog": "🐸",
    "monkey": "🐵",
    "gorilla": "🦍",
    "chicken": "🐔",
    "penguin": "🐧",
    "bird": "🐦",
    "chick": "🐤",
    "duck": "🦆",
    "eagle": "🦅",
    "owl": "🦉",
    "bat": "🦇",
    "wolf": "🐺",
    "boar": "🐗",
    "horse": "🐴",
    "unicorn": "🦄",
    "bee": "🐝",
    "caterpillar": "🐛",
    "butterfly": "🦋",
    "snail": "🐌",
    "ladybug": "🐞",
    "ant": "🐜",
    "cricket": "🦗",
    "spider": "🕷️",
    "scorpion": "🦂",
    "turtle": "🐢",
    "snake": "🐍",
    "lizard": "🦎",
    "dinosaur": "🦖",
    "octopus": "🐙",
    "squid": "🦑",
    "crab": "🦀",
    "fish": "🐟",
    "dolphin": "🐬",
    "shark": "🦈",
    "whale": "🐳",
    "crocodile": "🐊",
    "leopard": "🐆",
    "elephant": "🐘",
    "rhino": "🦏",
    "hippo": "🦛",
    "camel": "🐪",
    "giraffe": "🦒",
    "buffalo": "🐃",
    "ox": "🐂",
    "sheep": "🐑",
    "goat": "🐐",
    "deer": "🦌",
    "poodle": "🐩",
    "rooster": "🐓",
    "turkey": "🦃",
    "dove": "🕊️",
    "peacock": "🦚",
    "parrot": "🦜",
    "swan": "🦢",
    "flamingo": "🦩",
    "tree": "🌳",
    "palm": "🌴",
    "cactus": "🌵",
    "wheat": "🌾",
    "herb": "🌿",
    "clover": "☘️",
    "leaf": "🍁",
    "flower": "🌸",
    "sunflower": "🌻",
    "rose": "🌹",
    "tulip": "🌷",
    "seedling": "🌱",
    "chestnut": "🌰",
    "apple": "🍎",
    "orange": "🍊",
    "lemon": "🍋",
    "banana": "🍌",
    "watermelon": "🍉",
    "grapes": "🍇",
    "strawberry": "🍓",
    "melon": "🍈",
    "cherry": "🍒",
    "peach": "🍑",
    "mango": "🥭",
    "pineapple": "🍍",
    "coconut": "🥥",
    "kiwi": "🥝",
    "tomato": "🍅",
    "eggplant": "🍆",
    "avocado": "🥑",
    "broccoli": "🥦",
    "lettuce": "🥬",
    "cucumber": "🥒",
    "pepper": "🌶️",
    "corn": "🌽",
    "carrot": "🥕",
    "garlic": "🧄",
    "onion": "🧅",
    "potato": "🥔",
    "croissant": "🥐",
    "bread": "🍞",
    "pretzel": "🥨",
    "bagel": "🥯",
    "pancake": "🥞",
    "waffle": "🧇",
    "cheese": "🧀",
    "meat": "🍖",
    "steak": "🥩",
    "bacon": "🥓",
    "burger": "🍔",
    "fries": "🍟",
    "pizza": "🍕",
    "hotdog": "🌭",
    "sandwich": "🥪",
    "taco": "🌮",
    "burrito": "🌯",
    "salad": "🥗",
    "paella": "🥘",
    "pasta": "🍝",
    "noodle": "🍜",
    "stew": "🍲",
    "curry": "🍛",
    "sushi": "🍣",
    "bento": "🍱",
    "dumpling": "🥟",
    "shrimp": "🍤",
    "rice": "🍙",
    "fishcake": "🍥",
    "cookie": "🥠",
    "mooncake": "🥮",
    "oden": "🍢",
    "dango": "🍡",
    "ice": "🍧",
    "pie": "🥧",
    "cupcake": "🧁",
    "cake": "🍰",
    "pudding": "🍮",
    "candy": "🍭",
    "chocolate": "🍫",
    "popcorn": "🍿",
    "donut": "🍩",
    "peanut": "🥜",
    "honey": "🍯",
    "milk": "🥛",
    "bottle": "🍼",
    "coffee": "☕",
    "tea": "🍵",
    "sake": "🍶",
    "champagne": "🍾",
    "wine": "🍷",
    "cocktail": "🍸",
    "juice": "🍹",
    "beer": "🍺",
    "whiskey": "🥃",
    "soda": "🥤",
    "sun": "☀️",
    "cloud": "☁️",
    "rain": "🌧️",
    "storm": "⛈️",
    "lightning": "🌩️",
    "snow": "🌨️",
    "snowman": "☃️",
    "wind": "🌬️",
    "tornado": "🌪️",
    "fog": "🌫️",
    "rainbow": "🌈",
    "moon": "🌙",
    "star": "⭐",
    "sparkle": "✨",
    "dizzy": "💫",
    "comet": "☄️",
    "house": "🏠",
    "houses": "🏘️",
    "building": "🏗️",
    "factory": "🏭",
    "office": "🏢",
    "store": "🏬",
    "post": "🏣",
    "hospital": "🏥",
    "bank": "🏦",
    "hotel": "🏨",
    "school": "🏫",
    "church": "💒",
    "museum": "🏛️",
    "mosque": "🕌",
    "temple": "🛕",
    "synagogue": "🕍",
    "shrine": "⛩️",
    "japan": "🗾",
    "carousel": "🎠",
    "wheel": "🎡",
    "coaster": "🎢",
    "barber": "💈",
    "circus": "🎪",
    "car": "🚗",
    "taxi": "🚕",
    "bus": "🚌",
    "police": "🚓",
    "ambulance": "🚑",
    "truck": "🚛",
    "van": "🚐",
    "tractor": "🚜",
    "cane": "🦯",
    "wheelchair": "🦽",
    "scooter": "🛴",
    "bicycle": "🚲",
    "motorcycle": "🏍️",
    "rickshaw": "🛺",
    "siren": "🚨",
    "cable": "🚡",
    "monorail": "🚟",
    "tram": "🚋",
    "train": "🚂",
    "metro": "🚇",
    "station": "🚉",
    "airplane": "✈️",
    "seat": "💺",
    "helicopter": "🚁",
    "satellite": "🛰️",
    "rocket": "🚀",
    "ufo": "🛸",
    "canoe": "🛶",
    "sailboat": "⛵",
    "boat": "🚤",
    "ship": "🚢",
    "ferry": "⛴️",
    "anchor": "⚓",
    "fuel": "⛽",
    "construction": "🚧",
    "light": "🚦",
    "stop": "🚏",
    "map": "🗺️",
    "statue": "🗿",
    "tower": "🗼",
    "liberty": "🗽",
    "fountain": "⛲",
    "umbrella": "⛱️",
    "beach": "🏖️",
    "island": "🏝️",
    "ball": "⚽",
    "basketball": "🏀",
    "football": "🏈",
    "baseball": "⚾",
    "softball": "🥎",
    "tennis": "🎾",
    "volleyball": "🏐",
    "rugby": "🏉",
    "frisbee": "🥏",
    "pool": "🎱",
    "yoyo": "🪀",
    "ping": "🏓",
    "badminton": "🏸",
    "hockey": "🏒",
    "lacrosse": "🥍",
    "cricket": "🏏",
    "goal": "🥅",
    "golf": "⛳",
    "archery": "🏹",
    "fishing": "🎣",
    "diving": "🤿",
    "boxing": "🥊",
    "martial": "🥋",
    "shirt": "🎽",
    "skateboard": "🛹",
    "skate": "🛼",
    "curling": "🥌",
    "ski": "🎿",
    "snowboard": "🏂",
    "parachute": "🪂",
    "weight": "🏋️",
    "wrestling": "🤼",
    "cartwheel": "🤸",
    "fencing": "🤺",
    "handball": "🤾",
    "swim": "🏊",
    "surf": "🏄",
    "row": "🚣",
    "climb": "🧗",
    "bike": "🚴",
    "juggle": "🤹",
    "yoga": "🧘",
    "watch": "⌚",
    "phone": "📱",
    "computer": "💻",
    "keyboard": "⌨️",
    "printer": "🖨️",
    "mouse": "🖱️",
    "trackball": "🖲️",
    "joystick": "🕹️",
    "clamp": "🗜️",
    "disk": "💾",
    "cd": "💿",
    "dvd": "📀",
    "tape": "📼",
    "camera": "📷",
    "video": "📹",
    "projector": "📽️",
    "film": "🎞️",
    "pager": "📟",
    "fax": "📠",
    "tv": "📺",
    "radio": "📻",
    "microphone": "🎙️",
    "slider": "🎚️",
    "knobs": "🎛️",
    "compass": "🧭",
    "stopwatch": "⏱️",
    "timer": "⏲️",
    "clock": "⏰",
    "hourglass": "⌛",
    "battery": "🔋",
    "plug": "🔌",
    "bulb": "💡",
    "flashlight": "🔦",
    "candle": "🕯️",
    "lamp": "🪔",
    "extinguisher": "🧯",
    "drum": "🛢️",
    "money": "💰",
    "dollar": "💵",
    "yen": "💴",
    "euro": "💶",
    "pound": "💷",
    "card": "💳",
    "gem": "💎",
    "scale": "⚖️",
    "toolbox": "🧰",
    "wrench": "🔧",
    "hammer": "🔨",
    "tools": "🛠️",
    "pick": "⛏️",
    "bolt": "🔩",
    "gear": "⚙️",
    "brick": "🧱",
    "chain": "⛓️",
    "magnet": "🧲",
    "gun": "🔫",
    "bomb": "💣",
    "firecracker": "🧨",
    "axe": "🪓",
    "knife": "🔪",
    "sword": "🗡️",
    "swords": "⚔️",
    "shield": "🛡️",
    "cigarette": "🚬",
    "coffin": "⚰️",
    "urn": "⚱️",
    "amphora": "🏺",
    "beads": "📿",
    "alembic": "⚗️",
    "telescope": "🔭",
    "microscope": "🔬",
    "hole": "🕳️",
    "pill": "💊",
    "syringe": "💉",
    "bandage": "🩹",
    "stethoscope": "🩺",
    "door": "🚪",
    "elevator": "🛗",
    "mirror": "🪞",
    "window": "🪟",
    "bed": "🛏️",
    "couch": "🛋️",
    "chair": "🪑",
    "toilet": "🚽",
    "shower": "🚿",
    "bathtub": "🛁",
    "razor": "🪒",
    "lotion": "🧴",
    "pin": "🧷",
    "broom": "🧹",
    "basket": "🧺",
    "paper": "🧻",
    "soap": "🧼",
    "sponge": "🧽",
    "cart": "🛒",
    "glasses": "👓",
    "sunglasses": "🕶️",
    "goggles": "🥽",
    "coat": "🥼",
    "vest": "🦺",
    "tie": "👔",
    "jeans": "👖",
    "scarf": "🧣",
    "gloves": "🧤",
    "socks": "🧦",
    "dress": "👗",
    "kimono": "👘",
    "sari": "🥻",
    "swimsuit": "🩱",
    "underwear": "🩲",
    "shorts": "🩳",
    "bikini": "👙",
    "purse": "👛",
    "bag": "👜",
    "clutch": "👝",
    "backpack": "🎒",
    "shoe": "👞",
    "boot": "👢",
    "sandal": "👡",
    "heel": "👠",
    "crown": "👑",
    "hat": "👒",
    "cap": "🧢",
    "helmet": "⛑️",
    "lipstick": "💄",
    "ring": "💍",
    "briefcase": "💼",
    "heart": "❤️",
    "peace": "☮️",
    "cross": "✝️",
    "crescent": "☪️",
    "om": "🕉️",
    "menorah": "🕎",
    "yin": "☯️",
    "worship": "🛐",
    "ophiuchus": "⛎",
    "aries": "♈",
    "taurus": "♉",
    "gemini": "♊",
    "cancer": "♋",
    "leo": "♌",
    "virgo": "♍",
    "libra": "♎",
    "scorpio": "♏",
    "sagittarius": "♐",
    "capricorn": "♑",
    "aquarius": "♒",
    "pisces": "♓",
    "id": "🆔",
    "atom": "⚛️",
    "accept": "🉑",
    "radioactive": "☢️",
    "biohazard": "☣️",
    "off": "📴",
    "vibrate": "📳",
    "vs": "🆚",
    "bargain": "🉐",
    "secret": "㊙️",
    "congratulations": "㊗️",
    "pass": "🈴",
    "full": "🈵",
    "discount": "🈹",
    "prohibit": "🈲",
    "a": "🅰️",
    "b": "🅱️",
    "ab": "🆎",
    "cl": "🆑",
    "o": "🅾️",
    "sos": "🆘",
    "circle": "⭕",
    "entry": "⛔",
    "name": "📛",
    "prohibited": "🚫",
    "hundred": "💯",
    "anger": "💢",
    "hot": "♨️",
    "pedestrian": "🚷",
    "litter": "🚯",
    "water": "🚱",
    "underage": "🔞",
    "smoking": "🚭",
    "exclamation": "❗",
    "question": "❓",
    "wavy": "〽️",
    "warning": "⚠️",
    "children": "🚸",
    "trident": "🔱",
    "fleur": "⚜️",
    "beginner": "🔰",
    "recycle": "♻️",
    "check": "✅",
    "reserved": "🈯",
    "chart": "💹",
    "asterisk": "✳️",
    "m": "Ⓜ️",
    "cyclone": "🌀",
    "sleep": "💤",
    "atm": "🏧",
    "wc": "🚾",
    "parking": "🅿️",
    "vacancy": "🈳",
    "service": "🈂️",
    "passport": "🛂",
    "customs": "🛃",
    "baggage": "🛄",
    "luggage": "🛅",
    "men": "🚹",
    "women": "🚺",
    "baby": "🚼",
    "restroom": "🚻",
    "cinema": "🎦",
    "signal": "📶",
    "here": "🈁",
    "symbols": "🔣",
    "information": "ℹ️",
    "abc": "🔤",
    "abcd": "🔡",
    "capital": "🔠",
    "ng": "🆖",
    "ok": "🆗",
    "up": "🆙",
    "cool": "🆒",
    "new": "🆕",
    "free": "🆓",
    "zero": "0️⃣",
    "one": "1️⃣",
    "two": "2️⃣",
    "three": "3️⃣",
    "four": "4️⃣",
    "five": "5️⃣",
    "six": "6️⃣",
    "seven": "7️⃣",
    "eight": "8️⃣",
    "nine": "9️⃣",
    "ten": "🔟",
    "eye": "👁️",
    "eyes": "👀",
    "ear": "👂",
    "nose": "👃",
    "mouth": "👄",
    "tongue": "👅",
    "tooth": "🦷",
    "bone": "🦴",
    "child": "🧒",
    "boy": "👦",
    "girl": "👧",
    "person": "🧑",
    "man": "👨",
    "woman": "👩",
    "older": "🧓",
    "frown": "🙍",
    "pout": "🙎",
    "no": "🙅",
    "raise": "🙋",
    "deaf": "🧏",
    "bow": "🙇",
    "facepalm": "🤦",
    "shrug": "🤷",
    "detective": "🕵️",
    "guard": "💂",
    "prince": "🤴",
    "princess": "👸",
    "turban": "👳",
    "headscarf": "🧕",
    "tuxedo": "🤵",
    "bride": "👰",
    "pregnant": "🤰",
    "feeding": "🤱",
    "angel": "👼",
    "santa": "🎅",
    "superhero": "🦸",
    "supervillain": "🦹",
    "mage": "🧙",
    "fairy": "🧚",
    "vampire": "🧛",
    "merperson": "🧜",
    "elf": "🧝",
    "genie": "🧞",
    "zombie": "🧟",
    "massage": "💆",
    "haircut": "💇",
    "walk": "🚶",
    "stand": "🧍",
    "kneel": "🧎",
    "blind": "👨‍🦯",
    "run": "🏃",
    "dance": "💃",
    "suit": "🕴️",
    "bunny": "👯",
    "sauna": "🧖",
    "fence": "🤺",
    "polo": "🤽",
    "lotus": "🧘",
    "bath": "🛀",
    "couple": "👫",
    "kiss": "💏",
    "family": "👪",
    "speak": "🗣️",
    "bust": "👤",
    "busts": "👥",
    "footprints": "👣",
    "hands": "🤲",
    "clap": "👏",
    "handshake": "🤝",
    "thumbs": "👍",
    "fist": "👊",
    "fingers": "🤞",
    "victory": "✌️",
    "love": "🤟",
    "rock": "🤘",
    "pinch": "🤏",
    "left": "👈",
    "right": "👉",
    "down": "👇",
    "hand": "✋",
    "spock": "🖖",
    "wave": "👋",
    "call": "🤙",
    "muscle": "💪",
    "arm": "🦾",
    "finger": "🖕",
    "write": "✍️",
    "pray": "🙏",
    "foot": "🦶",
    "leg": "🦵",
    "ladder": "🪜",
    "plunger": "🪠",
    "bucket": "🪣",
    "fire": "🧯",
    "pencil": "✏️",
    "pen": "🖊️",
    "brush": "🖌️",
    "crayon": "🖍️",
    "memo": "📝",
    "folder": "📁",
    "dividers": "🗂️",
    "calendar": "📅",
    "notepad": "🗒️",
    "cards": "📇",
    "clipboard": "📋",
    "clip": "📎",
    "clips": "🖇️",
    "ruler": "📏",
    "triangle": "📐",
    "scissors": "✂️",
    "box": "🗃️",
    "cabinet": "🗄️",
    "trash": "🗑️",
    "lock": "🔒",
    "unlock": "🔓",
    "key": "🔑",
    "book": "📕",
    "notebook": "📔",
    "ledger": "📒",
    "page": "📃",
    "scroll": "📜",
    "newspaper": "📰",
    "bookmark": "📑",
    "label": "🏷️",
    "receipt": "🧾",
    "score": "🎼",
    "note": "🎵",
    "notes": "🎶",
    "headphone": "🎧",
    "saxophone": "🎷",
    "guitar": "🎸",
    "trumpet": "🎺",
    "violin": "🎻",
    "banjo": "🪕",
    "clapper": "🎬",
    "palette": "🎨",
    "slot": "🎰",
    "dice": "🎲",
    "dart": "🎯",
    "bowling": "🎳",
    "game": "🎮",
    "joker": "🃏",
    "mahjong": "🀄",
    "gift": "🎁",
    "ribbon": "🎀",
    "confetti": "🎊",
    "tanabata": "🎋",
    "dolls": "🎎",
    "carp": "🎏",
    "chime": "🎐",
    "envelope": "🧧",
    "party": "🎉",
}

# German word mapping (includes both base word and article forms)
GERMAN_WORD_TO_EMOJI = {
    "katze": "🐱",
    "die katze": "🐱",
    "hund": "🐶",
    "der hund": "🐶",
    "maus": "🐭",
    "die maus": "🐭",
    "hamster": "🐹",
    "der hamster": "🐹",
    "kaninchen": "🐰",
    "das kaninchen": "🐰",
    "fuchs": "🦊",
    "der fuchs": "🦊",
    "bär": "🐻",
    "der bär": "🐻",
    "panda": "🐼",
    "der panda": "🐼",
    "tiger": "🦁",
    "der tiger": "🦁",
    "löwe": "🦁",
    "der löwe": "🦁",
    "kuh": "🐮",
    "die kuh": "🐮",
    "schwein": "🐷",
    "das schwein": "🐷",
    "frosch": "🐸",
    "der frosch": "🐸",
    "affe": "🐵",
    "der affe": "🐵",
    "huhn": "🐔",
    "das huhn": "🐔",
    "pinguin": "🐧",
    "der pinguin": "🐧",
    "vogel": "🐦",
    "der vogel": "🐦",
    "küken": "🐤",
    "das küken": "🐤",
    "ente": "🦆",
    "die ente": "🦆",
    "adler": "🦅",
    "der adler": "🦅",
    "eule": "🦉",
    "die eule": "🦉",
    "fledermaus": "🦇",
    "die fledermaus": "🦇",
    "wolf": "🐺",
    "der wolf": "🐺",
    "pferd": "🐴",
    "das pferd": "🐴",
    "biene": "🐝",
    "die biene": "🐝",
    "schmetterling": "🦋",
    "der schmetterling": "🦋",
    "schnecke": "🐌",
    "die schnecke": "🐌",
    "ameise": "🐜",
    "die ameise": "🐜",
    "spinne": "🕷️",
    "die spinne": "🕷️",
    "schildkröte": "🐢",
    "die schildkröte": "🐢",
    "schlange": "🐍",
    "die schlange": "🐍",
    "fisch": "🐟",
    "der fisch": "🐟",
    "delfin": "🐬",
    "der delfin": "🐬",
    "wal": "🐳",
    "der wal": "🐳",
    "elefant": "🐘",
    "der elefant": "🐘",
    "giraffe": "🦒",
    "die giraffe": "🦒",
    "schaf": "🐑",
    "das schaf": "🐑",
    "ziege": "🐐",
    "die ziege": "🐐",
    "reh": "🦌",
    "das reh": "🦌",
    "hahn": "🐓",
    "der hahn": "🐓",
    "baum": "🌳",
    "der baum": "🌳",
    "blume": "🌸",
    "die blume": "🌸",
    "rose": "🌹",
    "die rose": "🌹",
    "blatt": "🍁",
    "das blatt": "🍁",
    "apfel": "🍎",
    "der apfel": "🍎",
    "orange": "🍊",
    "die orange": "🍊",
    "zitrone": "🍋",
    "die zitrone": "🍋",
    "banane": "🍌",
    "die banane": "🍌",
    "wassermelone": "🍉",
    "die wassermelone": "🍉",
    "trauben": "🍇",
    "die trauben": "🍇",
    "erdbeere": "🍓",
    "die erdbeere": "🍓",
    "kirsche": "🍒",
    "die kirsche": "🍒",
    "tomate": "🍅",
    "die tomate": "🍅",
    "karotte": "🥕",
    "die karotte": "🥕",
    "kartoffel": "🥔",
    "die kartoffel": "🥔",
    "brot": "🍞",
    "das brot": "🍞",
    "käse": "🧀",
    "der käse": "🧀",
    "fleisch": "🍖",
    "das fleisch": "🍖",
    "burger": "🍔",
    "der burger": "🍔",
    "pizza": "🍕",
    "die pizza": "🍕",
    "kuchen": "🍰",
    "der kuchen": "🍰",
    "bonbon": "🍭",
    "das bonbon": "🍭",
    "schokolade": "🍫",
    "die schokolade": "🍫",
    "keks": "🍪",
    "der keks": "🍪",
    "milch": "🥛",
    "die milch": "🥛",
    "wasser": "💧",
    "das wasser": "💧",
    "kaffee": "☕",
    "der kaffee": "☕",
    "tee": "🍵",
    "der tee": "🍵",
    "saft": "🍹",
    "der saft": "🍹",
    "bier": "🍺",
    "das bier": "🍺",
    "sonne": "☀️",
    "die sonne": "☀️",
    "wolke": "☁️",
    "die wolke": "☁️",
    "regen": "🌧️",
    "der regen": "🌧️",
    "schnee": "🌨️",
    "der schnee": "🌨️",
    "wind": "🌬️",
    "der wind": "🌬️",
    "regenbogen": "🌈",
    "der regenbogen": "🌈",
    "mond": "🌙",
    "der mond": "🌙",
    "stern": "⭐",
    "der stern": "⭐",
    "haus": "🏠",
    "das haus": "🏠",
    "gebäude": "🏗️",
    "das gebäude": "🏗️",
    "schule": "🏫",
    "die schule": "🏫",
    "krankenhaus": "🏥",
    "das krankenhaus": "🏥",
    "kirche": "💒",
    "die kirche": "💒",
    "auto": "🚗",
    "das auto": "🚗",
    "bus": "🚌",
    "der bus": "🚌",
    "zug": "🚂",
    "der zug": "🚂",
    "fahrrad": "🚲",
    "das fahrrad": "🚲",
    "flugzeug": "✈️",
    "das flugzeug": "✈️",
    "boot": "🚤",
    "das boot": "🚤",
    "schiff": "🚢",
    "das schiff": "🚢",
    "ball": "⚽",
    "der ball": "⚽",
    "uhr": "⌚",
    "die uhr": "⌚",
    "telefon": "📱",
    "das telefon": "📱",
    "computer": "💻",
    "der computer": "💻",
    "kamera": "📷",
    "die kamera": "📷",
    "fernseher": "📺",
    "der fernseher": "📺",
    "geld": "💰",
    "das geld": "💰",
    "hammer": "🔨",
    "der hammer": "🔨",
    "messer": "🔪",
    "das messer": "🔪",
    "tür": "🚪",
    "die tür": "🚪",
    "fenster": "🪟",
    "das fenster": "🪟",
    "bett": "🛏️",
    "das bett": "🛏️",
    "stuhl": "🪑",
    "der stuhl": "🪑",
    "tisch": "🍽️",
    "der tisch": "🍽️",
    "brille": "👓",
    "die brille": "👓",
    "hemd": "👕",
    "das hemd": "👕",
    "hose": "👖",
    "die hose": "👖",
    "kleid": "👗",
    "das kleid": "👗",
    "schuh": "👞",
    "der schuh": "👞",
    "hut": "👒",
    "der hut": "👒",
    "herz": "❤️",
    "das herz": "❤️",
    "hand": "✋",
    "die hand": "✋",
    "fuß": "🦶",
    "der fuß": "🦶",
    "auge": "👁️",
    "das auge": "👁️",
    "ohr": "👂",
    "das ohr": "👂",
    "nase": "👃",
    "die nase": "👃",
    "mund": "👄",
    "der mund": "👄",
    "zahn": "🦷",
    "der zahn": "🦷",
    "baby": "👶",
    "das baby": "👶",
    "kind": "🧒",
    "das kind": "🧒",
    "junge": "👦",
    "der junge": "👦",
    "mädchen": "👧",
    "das mädchen": "👧",
    "mann": "👨",
    "der mann": "👨",
    "frau": "👩",
    "die frau": "👩",
    "buch": "📕",
    "das buch": "📕",
    "stift": "🖊️",
    "der stift": "🖊️",
    "bleistift": "✏️",
    "der bleistift": "✏️",
    "papier": "📃",
    "das papier": "📃",
    "schlüssel": "🔑",
    "der schlüssel": "🔑",
    "geschenk": "🎁",
    "das geschenk": "🎁",
    "ballon": "🎈",
    "der ballon": "🎈",
    "flagge": "🏳️",
    "die flagge": "🏳️",
}


def find_emoji_for_word(word: str, lang: str) -> str:
    """Find emoji for a given word based on language."""
    word_lower = word.lower().strip()

    if lang == "en-GB":
        return WORD_TO_EMOJI.get(word_lower, "❓")
    elif lang == "de-DE":
        return GERMAN_WORD_TO_EMOJI.get(word_lower, "❓")
    else:
        return "❓"


def main():
    parser = argparse.ArgumentParser(
        description="Import new phrases from text file into YAML"
    )
    parser.add_argument("input_file", help="Input text file with phrases (one per line)")
    parser.add_argument("yaml_file", help="Target YAML file (phrases-{lang}.yaml)")
    parser.add_argument(
        "--skip-ipa",
        action="store_true",
        help="Skip running update-ipa.ts"
    )
    parser.add_argument(
        "--skip-difficulty",
        action="store_true",
        help="Skip running update-difficulty.py"
    )

    args = parser.parse_args()

    input_file = Path(args.input_file)
    yaml_file = Path(args.yaml_file)

    # Validate files
    if not input_file.exists():
        print(f"Error: Input file not found: {input_file}", file=sys.stderr)
        sys.exit(1)

    if not yaml_file.exists():
        print(f"Error: YAML file not found: {yaml_file}", file=sys.stderr)
        sys.exit(1)

    # Extract language from YAML filename
    import re
    lang_match = re.search(r"phrases-([a-zA-Z-]+)\.yaml", yaml_file.name)
    if not lang_match:
        print("Error: Could not determine language from YAML filename", file=sys.stderr)
        print("Expected format: phrases-{lang}.yaml", file=sys.stderr)
        sys.exit(1)

    lang = lang_match.group(1)
    print(f"Language: {lang}")
    print()

    # Load existing phrases
    print(f"📖 Loading existing phrases from {yaml_file}...")
    with open(yaml_file, "r", encoding="utf-8") as f:
        existing_phrases = yaml.safe_load(f) or []

    if not isinstance(existing_phrases, list):
        print("Error: Invalid YAML format - expected list", file=sys.stderr)
        sys.exit(1)

    # Build set of existing phrase texts (case-insensitive for better deduplication)
    existing_texts = {p.get("phrase", "").lower() for p in existing_phrases}
    print(f"  Found {len(existing_phrases)} existing phrases")
    print()

    # Load new phrases from input file
    print(f"📖 Loading new phrases from {input_file}...")
    with open(input_file, "r", encoding="utf-8") as f:
        new_phrases_raw = [line.strip() for line in f if line.strip()]

    print(f"  Found {len(new_phrases_raw)} phrases in input file")
    print()

    # Filter out duplicates and create phrase entries
    new_entries = []
    skipped = []

    for phrase_text in new_phrases_raw:
        phrase_lower = phrase_text.lower()

        if phrase_lower in existing_texts:
            skipped.append(phrase_text)
            continue

        # Find emoji for this phrase
        emoji = find_emoji_for_word(phrase_text, lang)

        # Create new entry
        new_entry = {
            "phrase": phrase_text,
            "emoji": emoji
        }

        new_entries.append(new_entry)
        existing_texts.add(phrase_lower)  # Add to set to avoid duplicates within new phrases

    print("=" * 70)
    print(f"New phrases to add: {len(new_entries)}")
    print(f"Duplicates skipped: {len(skipped)}")
    print("=" * 70)
    print()

    if len(skipped) > 0 and len(skipped) <= 10:
        print("Skipped duplicates:")
        for s in skipped:
            print(f"  - {s}")
        print()

    if len(new_entries) == 0:
        print("✅ No new phrases to add!")
        sys.exit(0)

    # Add new entries to the list
    all_phrases = existing_phrases + new_entries

    # Write back to YAML file
    print(f"✍️  Writing {len(new_entries)} new phrases to {yaml_file}...")
    with open(yaml_file, "w", encoding="utf-8") as f:
        yaml.dump(
            all_phrases,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
            width=100,
        )

    print(f"✅ Added {len(new_entries)} new phrases to {yaml_file}")
    print()

    # Run update-ipa.ts if not skipped
    if not args.skip_ipa:
        print("🔄 Running update-ipa.ts to add IPA pronunciations...")
        try:
            result = subprocess.run(
                ["./run", "tsx", "scripts/update-ipa.ts", str(yaml_file)],
                cwd=yaml_file.parent.parent,
                capture_output=False,
                text=True
            )
            if result.returncode != 0:
                print("⚠️  Warning: update-ipa.ts failed", file=sys.stderr)
            else:
                print("✅ IPA pronunciations added")
        except Exception as e:
            print(f"⚠️  Warning: Could not run update-ipa.ts: {e}", file=sys.stderr)
        print()

    # Run update-difficulty.py if not skipped
    if not args.skip_difficulty:
        print("🔄 Running update-difficulty.py to add difficulty scores...")
        try:
            result = subprocess.run(
                ["./run", "python3", "scripts/update-difficulty.py", str(yaml_file)],
                cwd=yaml_file.parent.parent,
                capture_output=False,
                text=True
            )
            if result.returncode != 0:
                print("⚠️  Warning: update-difficulty.py failed", file=sys.stderr)
            else:
                print("✅ Difficulty scores added")
        except Exception as e:
            print(f"⚠️  Warning: Could not run update-difficulty.py: {e}", file=sys.stderr)
        print()

    print("=" * 70)
    print("✅ Import complete!")
    print(f"  Total phrases in {yaml_file}: {len(all_phrases)}")
    print("=" * 70)


if __name__ == "__main__":
    main()
